/*
 * Card:
 *   ID Name Description Event Border Stars Place Place2 Prototype Shape Attribute HP MP ATK DEF AGI WIS 
 *   Skills Recommends RecommendsRB
 */
Card.addAll(new Array(
    new Array("30001", "Suzaku", "The spirit bird that defends the southern heavens, purging calamity by fire and bringing good luck.",
              Event.bahamut, Border.none, 4, Place.volcano, 0, null, Shape.lbird, Attribute.fire,
              794, 898, 830, 866, 912, 892,
              new Array(Skill.fire2, Skill.physical2, Skill.physical3, Skill.fire3, Skill.atk20, Skill.wis20),
              new Array(Skill.physical3, Skill.fire3, Skill.atk20),
              new Array(Skill.fire3, Skill.atk20, Skill.wis20)),
    new Array("30003", "Kraken", "A colossal monster that lurks in the depths of sea, surfacing to attack ships with its gigantic tentacles.", 
              Event.none, Border.none, 4, Place.plains, 0, null, Shape.dragon, Attribute.water, 
              830, 720, 915, 800, 760, 780, 
              new Array(Skill.water2, Skill.atk20, Skill.physical2, Skill.def20, Skill.physical3, Skill.atkdef10),
              new Array(Skill.atk20, Skill.def20, Skill.physical3),
              new Array(Skill.atk20, Skill.physical3, Skill.atkdef10)),
    new Array("30004", "Genbu", "The spirit tortoise that defends the northern heavens, guarding against calamity and bringing prosperity.", 
              Event.bahamut, Border.none, 4, Place.volcano, 0, null, Shape.lwolf, Attribute.water,
              868, 902, 810, 940, 830, 880,
              new Array(Skill.physical2, Skill.def20, Skill.wis20, Skill.physical3, Skill.atk20, Skill.water3),
              new Array(Skill.wis20, Skill.physical3, Skill.atk20),
              new Array(Skill.wis20, Skill.atk20, Skill.water3)),
    new Array("30005", "Golem", "A figure crafted of clay and imbued with the breath of life to faithfully carry out its maker's wishes.", 
              Event.none, Border.none, 4, Place.volcano, 0, null, Shape.giant, Attribute.earth,
              966, 820, 966, 966, 800, 760, 
              new Array(Skill.physical2, Skill.atk10, Skill.physical3, Skill.def20, Skill.atk20, Skill.ls),
              new Array(Skill.atk10, Skill.physical3, Skill.atk20),
              new Array(Skill.physical3, Skill.atk20, Skill.ls)),
    new Array("30006", "Jormungandr", "This colossal serpent encircles the world, and is fated to battle the gods come the end of days.", 
              Event.none, Border.none, 4, Place.plains, 0, null, Shape.dragon, Attribute.earth,
              924, 896, 820, 850, 790, 829,
              new Array(Skill.earth2, Skill.atk20, Skill.earth3, Skill.def20, Skill.physical3, Skill.atkdef10),
              new Array(Skill.atk20, Skill.def20, Skill.physical3),
              new Array(Skill.atk20, Skill.physical3, Skill.atkdef10)),
    new Array("30007", "Seiryu", "The spirit dragon that defends the eastern heavens, bringing good fortune to the lands below it.", 
              Event.bahamut, Border.none, 4, Place.volcano, 0, null, Shape.lorbs, Attribute.lightning,
              868, 794, 889, 900, 903, 862, 
              new Array(Skill.physical2, Skill.def20, Skill.lightning2, Skill.majorheal, Skill.physical3, Skill.defagi10),
              new Array(Skill.def20, Skill.lightning2, Skill.physical3),
              new Array(Skill.def20, Skill.physical3, Skill.defagi10)),
    new Array("30008", "Hecatoncheir", "This grotesque giant bears immense power in its one hundred arms, for which even the gods fear it.", 
              Event.none, Border.none, 4, Place.plains, 0, null, Shape.giant, Attribute.lightning,
              822, 835, 899, 850, 830, 851,
              new Array(Skill.atk10, Skill.slash2, Skill.atk20, Skill.slash3, Skill.def20, Skill.atkwis10),
              new Array(Skill.atk10, Skill.atk20, Skill.slash3),
              new Array(Skill.atk20, Skill.slash3, Skill.atkwis10)),
    new Array("30009", "Ramiel", "This angel, whose name means \"thunder of the gods\", conveys the divine word through visions.", 
              Event.none, Border.none, 4, Place.plains, 0, null, Shape.humanoid, Attribute.lightning,
              800, 802, 816, 773, 816, 803,
              new Array(Skill.lightning2, Skill.wis20, Skill.lightning3, Skill.mana, Skill.majorheal, Skill.defwis10),
              new Array(Skill.lightning2, Skill.wis20, Skill.lightning3),
              new Array(Skill.wis20, Skill.lightning3, Skill.defwis10)),
    new Array("30010", "Garuda", "Glowing bright as if ablaze, this avian spirit brought an end to many gods in the battle for the elixir of life.", 
              Event.none, Border.none, 4, Place.volcano, 0, null, Shape.bird, Attribute.wind,
              848, 872, 848, 796, 886, 848,
              new Array(Skill.wind2, Skill.physical2, Skill.agi20, Skill.physical3, Skill.dwis20, Skill.wind3),
              new Array(Skill.agi20, Skill.physical3, Skill.dwis20),
              new Array(Skill.agi20, Skill.dwis20, Skill.wind3)),
    new Array("30011", "Wyvern", "Smaller than its dragon kin, the wyvern is more gifted in flight and bears a poisonous barb on its tail.", 
              Event.none, Border.none, 4, Place.volcano, 0, null, Shape.dragon, Attribute.wind,
              774, 798, 866, 850, 890, 842,
              new Array(Skill.wind2, Skill.poison2, Skill.physical2, Skill.wind3, Skill.agi20, Skill.defagi10),
              new Array(Skill.physical2, Skill.wind3, Skill.agi20),
              new Array(Skill.physical2, Skill.wind3, Skill.defagi10)),
    new Array("30012", "Medusa", "Even in death, the eyes of this foul, serpent-haired temptress turn all who gaze upon them to stone.", 
              Event.none, Border.none, 4, Place.volcano, 0, null, Shape.humanoid, Attribute.poison,
              819, 882, 824, 820, 844, 823, 
              new Array(Skill.poison2, Skill.physical2, Skill.dagi20, Skill.poison3, Skill.physical3, Skill.wis25),
              new Array(Skill.dagi20, Skill.poison3, Skill.physical3),
              new Array(Skill.poison3, Skill.physical3, Skill.wis25)),
    new Array("30013", "Vampire", "The bastard offspring of a lamia that hunts the living, unable to resist its instinctive thirst for blood.", 
              Event.none, Border.none, 4, Place.plains, 0, null, Shape.humanoid, Attribute.death,
              835, 914, 906, 835, 882, 910, 
              new Array(Skill.life, Skill.atk20, Skill.mana, Skill.agi20, Skill.slash3, Skill.revival),
              new Array(Skill.atk20, Skill.agi20, Skill.slash3),
              new Array(Skill.atk20, Skill.slash3, Skill.revival)),
    new Array("30015", "Byakko", "The spirit tiger that defends the western heavens, using its powers to maintain peace and tranquility.", 
              Event.bahamut, Border.none, 4, Place.volcano, 0, null, Shape.lwolf, Attribute.mecha,
              869, 822, 895, 902, 840, 893,
              new Array(Skill.def20, Skill.physical2, Skill.physical3, Skill.atk20, Skill.agi20, Skill.atkdef10),
              new Array(Skill.physical3, Skill.atk20, Skill.agi20),
              new Array(Skill.physical3, Skill.atk20, Skill.atkdef10)),
    new Array("30017", "Angel", "A celestial envoy that visits man on behalf of the gods, and fights to defend him from the minions of hell.", 
              Event.none, Border.none, 4, Place.plains, 0, null, Shape.humanoid, Attribute.light,
              764, 873, 860, 751, 866, 924,
              new Array(Skill.light2, Skill.heal, Skill.light3, Skill.majorheal, Skill.def20, Skill.wis20),
              new Array(Skill.light2, Skill.light3, Skill.def20),
              new Array(Skill.light3, Skill.def20, Skill.wis20)),
    new Array("30018", "Fenrir", "So feared is this great wolf that it was once bound captive by the gods. Now free, it thirsts for revenge.", 
              Event.none, Border.none, 4, Place.volcano, 0, null, Shape.wolf, Attribute.darkness,
              792, 754, 852, 792, 848, 760,
              new Array(Skill.physical2, Skill.agi20, Skill.physical3, Skill.atk20, Skill.ddef20, Skill.atkagi10),
              new Array(Skill.physical3, Skill.atk20, Skill.ddef20),
              new Array(Skill.physical3, Skill.atk20, Skill.ddef20)),
    new Array("30019", "Gold Slime", "This mutated slime is ill-suited to battle, though it is known to serve as an excellent combining material.", 
              Event.none, Border.none, 4, Place.grounds, 0, null, Shape.slime, Attribute.none,
              50, 50, 5, 5, 5, 5,
              new Array(Skill.heal),
              new Array(Skill.heal),
              new Array(Skill.heal)),
    new Array("30021", "Cerberus (FFXI)", "A terror in the Near East, this fire-breathing canine is the bane of trolls. - FINAL FANTASY XI", 
              Event.none, Border.none, 4, Place.invitation, 1, null, Shape.wolf, Attribute.fire,
              856, 808, 877, 857, 851, 846,
              new Array(Skill.fire2, Skill.def10, Skill.fire3, Skill.def20, Skill.agi20, Skill.wis20),
              new Array(Skill.fire3, Skill.def20, Skill.agi20),
              new Array(Skill.fire3, Skill.def20, Skill.wis20)),
    new Array("30025", "Giant", "Spawned by an ancient goddess, these huge beings are feared by the new gods for their great strength.", 
              Event.none, Border.none, 4, Place.volcano, 0, null, Shape.giant, Attribute.earth,
              892, 760, 872, 774, 766, 764,
              new Array(Skill.physical2, Skill.atk20, Skill.ddef20, Skill.def20, Skill.physical3, Skill.atkagi10),
              new Array(Skill.atk20, Skill.ddef20, Skill.physical3),
              new Array(Skill.atk20, Skill.ddef20, Skill.physical3)),
    new Array("30026", "Dullahan", "A headless knight drawn by the scent of coming death. His great blade reaps the souls of those it fells.", 
              Event.none, Border.none, 4, Place.volcano, 0, null, Shape.giant, Attribute.death,
              828, 877, 864, 886, 812, 841,
              new Array(Skill.slash2, Skill.def20, Skill.agi20, Skill.atk20, Skill.slash3, Skill.qs),
              new Array(Skill.agi20, Skill.atk20, Skill.slash3),
              new Array(Skill.atk20, Skill.slash3, Skill.qs)),
    new Array("30027", "Pazuzu", "This dread demon of storms and drought controls searing winds that visit feverish maladies upon man.", 
              Event.none, Border.none, 4, Place.plains, 0, null, Shape.wolf, Attribute.wind,
              742, 815, 860, 804, 802, 789,
              new Array(Skill.wind2, Skill.fire3, Skill.physical3, Skill.datk20, Skill.wind3, Skill.atk25),
              new Array(Skill.physical3, Skill.datk20, Skill.wind3),
              new Array(Skill.physical3, Skill.datk20, Skill.atk25)),
    new Array("30028", "Pabilsag", "This fierce guardian wards the mountain gateway between the celestial realm and the netherworld.", 
              Event.none, Border.none, 4, Place.volcano, 0, null, Shape.wolf, Attribute.poison,
              751, 960, 830, 860, 800, 890, 
              new Array(Skill.poison2, Skill.wis20, Skill.slash2, Skill.def20, Skill.slash3, Skill.poison4),
              new Array(Skill.wis20, Skill.def20, Skill.slash3),
              new Array(Skill.wis20, Skill.def20, Skill.poison4)),
    new Array("30030", "Qiong-Ji", "This bring controls the winds, summon forth freezing gales, and is ever on the side of evil.", 
              Event.none, Border.none, 4, Place.plains, 0, null, Shape.giant, Attribute.wind,
              890, 784, 982, 778, 932, 882,
              new Array(Skill.wind1, Skill.agi10, Skill.wind2, Skill.dagi20, Skill.agi20, Skill.wind3),
              new Array(Skill.wind2, Skill.dagi20, Skill.agi20),
              new Array(Skill.dagi20, Skill.agi20, Skill.wind3)),
    new Array("30031", "Revenant", "Reanimated by supernatural powers, this warrior retains in death the intellect and will it had in life.", 
              Event.none, Border.none, 4, Place.plains, 0, null, Shape.orbs, Attribute.death,
              999, 777, 957, 798, 782, 807,
              new Array(Skill.darkness1, Skill.physical1, Skill.darkness2, Skill.physical2, Skill.darkness3, Skill.atk20),
              new Array(Skill.darkness2, Skill.physical2, Skill.darkness3),
              new Array(Skill.physical2, Skill.darkness3, Skill.atk20)),
    new Array("30033", "Fafnir", "It is said to bathe in the blood of this dragon, which guards a cursed treasure, is to become immortal.", 
              Event.none, Border.none, 4, Place.snowfield, 0, null, Shape.dragon, Attribute.fire,
              858, 764, 878, 861, 768, 767, 
              new Array(Skill.slash2, Skill.ddef20, Skill.def10, Skill.datk20, Skill.slash3, Skill.atkdef10),
              new Array(Skill.ddef20, Skill.datk20, Skill.slash3),
              new Array(Skill.ddef20, Skill.slash3, Skill.atkdef10)),
    new Array("30034", "Jotunn", "Despite their savage and barbaric ways, the strength of these frost giants rivals the gods themselves.", 
              Event.none, Border.none, 4, Place.snowfield, 0, null, Shape.giant, Attribute.water, 
              940, 770, 932, 882, 765, 856, 
              new Array(Skill.water2, Skill.physical2, Skill.dagi20, Skill.water3, Skill.slash3, Skill.atkwis10),
              new Array(Skill.dagi20, Skill.water3, Skill.slash3),
              new Array(Skill.water3, Skill.slash3, Skill.atkwis10)),
    new Array("30035", "Specter", "This evil spirit emits a deathly chill, and the soul of any who gazes upon it freezes over with terror.", 
              Event.none, Border.none, 4, Place.snowfield, 0, null, Shape.orbs, Attribute.death,
              790, 957, 815, 815, 798, 907, 
              new Array(Skill.darkness2, Skill.water2, Skill.mana, Skill.darkness3, Skill.water3, Skill.sd),
              new Array(Skill.darkness2, Skill.darkness3, Skill.water3),
              new Array(Skill.darkness3, Skill.water3, Skill.sd)),
    new Array("30037", "Talos", "Imbued with the power of fire, this bronze titan guards an island where an ancient kingdom once stood.", 
              Event.none, Border.none, 4, Place.snowfield, 0, null, Shape.giant, Attribute.mecha,
              949, 767, 957, 940, 771, 798,
              new Array(Skill.slash2, Skill.fire2, Skill.def20, Skill.slash3, Skill.fire3, Skill.atkdef10),
              new Array(Skill.def20, Skill.slash3, Skill.fire3),
              new Array(Skill.def20, Skill.slash3, Skill.atkdef10)),
    new Array("30038", "Power", "These angels stand on the frontlines of battle against evil, and are therefore most easily corrupted by it.", 
              Event.none, Border.none, 4, Place.snowfield, 0, null, Shape.humanoid, Attribute.light,
              896, 913, 1010, 830, 858, 876,
              new Array(Skill.light2, Skill.slash2, Skill.light3, Skill.darkness3, Skill.slash3, Skill.atkwis10),
              new Array(Skill.light3, Skill.darkness3, Skill.slash3),
              new Array(Skill.darkness3, Skill.physical3, Skill.atkwis10)),
    new Array("30040", "Anahita", "This maiden deity of bounty rules over the fount of life, keeping vigil over health and child, crop and livestock.", 
              Event.none, Border.none, 4, Place.invitation, 2, null, Shape.humanoid, Attribute.water,
              929, 846, 779, 885, 843, 871,
              new Array(Skill.water2, Skill.wis10, Skill.heal, Skill.water3, Skill.def20, Skill.wis20),
              new Array(Skill.wis10, Skill.water3, Skill.def20),
              new Array(Skill.wis10, Skill.water3, Skill.wis20)),
    new Array("30041", "Peri", "This fiery and ephemeral faerie, born forth from flame itself, lives by consuming fragrances alone.", 
              Event.none, Border.none, 4, Place.invitation, 2, null, Shape.bird, Attribute.fire,
              861, 894, 795, 825, 851, 920,
              new Array(Skill.fire2, Skill.dwis20, Skill.mana, Skill.fire3, Skill.wis20, Skill.defwis10),
              new Array(Skill.dwis20, Skill.fire3, Skill.wis20),
              new Array(Skill.dwis20, Skill.fire3, Skill.wis20)),
    new Array("30042", "Virtus", "This embodiment of purest virtue works miracles and grants the favor of the gods to champions of good.", 
              Event.none, Border.none, 4, Place.invitation, 2, null, Shape.humanoid, Attribute.light,
              859, 847, 881, 929, 786, 843,
              new Array(Skill.light2, Skill.agi20, Skill.light3, Skill.wis20, Skill.atk20, Skill.dwis20),
              new Array(Skill.agi20, Skill.light3, Skill.wis20),
              new Array(Skill.light3, Skill.wis20, Skill.dwis20)),
    new Array("30043", "Caim", "Versed in all languages, this devilish god sways the minds of mortals with words both clever and cunning.", 
              Event.none, Border.none, 4, Place.volcano, 0, null, Shape.humanoid, Attribute.fire,
              845, 905, 815, 863, 844, 943,
              new Array(Skill.slash2, Skill.wis20, Skill.fire2, Skill.life, Skill.dwis20, Skill.agiwis10),
              new Array(Skill.wis20, Skill.fire2, Skill.dwis20),
              new Array(Skill.wis20, Skill.fire2, Skill.dwis20)),
    new Array("30044", "Brigid", "This noble fire goddess expels winter fiends with flames from her magic brazier, ushering in the start of spring.", 
              Event.none, Border.none, 4, Place.volcano, 0, null, Shape.humanoid, Attribute.fire,
              825, 929, 789, 887, 833, 929,
              new Array(Skill.fire2, Skill.heal, Skill.fire3, Skill.majorheal, Skill.wis20, Skill.defwis10),
              new Array(Skill.fire2, Skill.fire3, Skill.wis20),
              new Array(Skill.fire3, Skill.wis20, Skill.defwis10)),
    new Array("30045", "Aym", "Armed with his undying torch, this fire demon and duke of hell sets the proud cities of man ablaze.", 
              Event.none, Border.none, 4, Place.desert, 0, null, Shape.orbs, Attribute.fire,
              815, 865, 935, 822, 857, 850,
              new Array(Skill.fire2, Skill.physical2, Skill.atk10, Skill.atk20, Skill.sd, Skill.atkwis10),
              new Array(Skill.physical2, Skill.atk10, Skill.atk20),
              new Array(Skill.physical2, Skill.atk20, Skill.atkwis10)),
    new Array("30046", "Atar", "Lesser deity and son of a benevolent god, this warrior of good and spirit of holy fire protects the world from evil.", 
              Event.none, Border.none, 4, Place.desert, 0, null, Shape.humanoid, Attribute.fire,
              873, 817, 871, 919, 865, 875,
              new Array(Skill.fire2, Skill.heal, Skill.atk20, Skill.qs, Skill.fire3, Skill.wis20),
              new Array(Skill.fire3, Skill.atk20, Skill.qs),
              new Array(Skill.fire3, Skill.qs, Skill.wis20)),
    new Array("30047", "Rudra", "Mortals fear this malevolent god of wind and storm, yet praise him as the lord of bounty who sends the nurturing rains.", 
              Event.none, Border.none, 4, Place.desert, 0, null, Shape.female, Attribute.wind,
              845, 901, 905, 816, 891, 985, 
              new Array(Skill.wind2, Skill.agi10, Skill.heal, Skill.wind3, Skill.agi20, Skill.agiwis10),
              new Array(Skill.agi10, Skill.wind3, Skill.agi20),
              new Array(Skill.wind3, Skill.agi20, Skill.agiwis10)),
    new Array("30048", "Taowu", "This wicked demon plots all mayhem that transpires, and is too arrogant and stubborn to ever concede defeat.", 
              Event.none, Border.none, 4, Place.desert, 0, null, Shape.wolf, Attribute.poison,
              911, 781, 919, 901, 793, 839,
              new Array(Skill.poison1, Skill.def10, Skill.def20, Skill.poison2, Skill.ls, Skill.atk20),
              new Array(Skill.def20, Skill.poison2, Skill.ls),
              new Array(Skill.poison2, Skill.ls, Skill.atk20)),
    new Array("30049", "Narasimha", "This avatar of a higher god is both man and lion, with a strength and ferocity to tear apart even the most deathless evil.", 
              Event.none, Border.none, 4, Place.desert, 0, null, Shape.orbs, Attribute.lightning,
              843, 815, 999, 835, 903, 795,
              new Array(Skill.atk10, Skill.lightning2, Skill.slash3, Skill.atk20, Skill.lightning3, Skill.agi20),
              new Array(Skill.atk10, Skill.slash3, Skill.atk20),
              new Array(Skill.atk10, Skill.slash3, Skill.atk20)),
    new Array("30050", "Barong", "The manifestation of good itself, this holy beast is fated to battle evil and protect mortals from coming to harm.", 
              Event.none, Border.none, 4, Place.desert, 0, null, Shape.wolf, Attribute.light,
              879, 833, 891, 901, 839, 819,
              new Array(Skill.light2, Skill.physical2, Skill.def20, Skill.wis20, Skill.light3, Skill.atk20),
              new Array(Skill.def20, Skill.wis20, Skill.light3),
              new Array(Skill.wis20, Skill.light3, Skill.atk20)),
    new Array("30051", "Horus", "This divinity of the skies is the symbol of royalty. Its eyes hold power over the sun and moon and see the truth of all things.", 
              Event.none, Border.none, 4, Place.desert, 0, null, Shape.bird, Attribute.light,
              794, 835, 799, 889, 849, 909, 
              new Array(Skill.slash2, Skill.qs, Skill.light2, Skill.wis20, Skill.light3, Skill.defwis10),
              new Array(Skill.qs, Skill.wis20, Skill.light3),
              new Array(Skill.qs, Skill.wis20, Skill.light3)),
    new Array("30057", "Skadi", "Born of giants, this vengeful goddess and huntress of the north wields a bow and fears no enemy or quarry.", 
              Event.none, Border.none, 4, Place.snowfield, 0, null, Shape.female, Attribute.water, 
              925, 828, 925, 852, 925, 872, 
              new Array(Skill.physical2, Skill.water2, Skill.physical3, Skill.agi10, Skill.water3, Skill.agi20),
              new Array(Skill.physical3, Skill.agi10, Skill.water3),
              new Array(Skill.physical3, Skill.water3, Skill.agi20)),
    new Array("30058", "Forneus", "As the keeper of language, this sea monster and marquis of Hell can turn even the most dire animosity to love.", 
              Event.none, Border.none, 4, Place.snowfield, 0, null, Shape.dragon, Attribute.water,
              885, 907, 825, 847, 825, 930,
              new Array(Skill.water1, Skill.water2, Skill.datk20, Skill.dwis20, Skill.water3, Skill.wis20),
              new Array(Skill.datk20, Skill.dwis20, Skill.water3),
              new Array(Skill.dwis20, Skill.water3, Skill.wis20)),
			  
	new Array("30056", "Balor", "Known as Balor of the Evil Eye, this ancient demon king's gaze consigns all who look upon it to oblivion.", 
              Event.gilgamesh, Border.none, 4, Place.volcano, 0, null, Shape.giant, Attribute.darkness,
              928, 881, 837, 907, 835, 850,
              new Array(Skill.darkness2, Skill.dagi20, Skill.ddef20, Skill.wis10, Skill.darkness3, Skill.wis20),
              new Array(Skill.dagi20, Skill.wis10, Skill.darkness3),
              new Array(Skill.wis10, Skill.darkness3, Skill.wis20)),
    new Array("30053", "Bugbear", "Strong and thickly furred, these beasts appear at twilight to snatch up children who play past the calls of their mothers.", 
              Event.gilgamesh, Border.none, 4, Place.volcano, 0, null, Shape.giant, Attribute.earth,
              943, 830, 871, 893, 851, 810, 
              new Array(Skill.earth2, Skill.physical2, Skill.ddef20, Skill.physical3, Skill.earth3, Skill.revival),
              new Array(Skill.ddef20, Skill.physical3, Skill.earth3),
              new Array(Skill.ddef20, Skill.physical3, Skill.revival)),
    new Array("30054", "Bune", "With necromancy, this Great Duke of Hell commands the dead and summons demons to the world's graveyards.", 
              Event.gilgamesh, Border.none, 4, Place.volcano, 0, null, Shape.giant, Attribute.death, 
              891, 909, 860, 924, 820, 935, 
              new Array(Skill.def20, Skill.death2, Skill.wis20, Skill.darkness2, Skill.revival, Skill.agi20),
              new Array(Skill.death2, Skill.wis20, Skill.revival),
              new Array(Skill.death2, Skill.wis20, Skill.revival)),
    new Array("30055", "Dwarf Gear", "This armored terror boasts engines and crystals of Dwarvish making, and can be ridden only by the heroic of heart.", 
              Event.gilgamesh, Border.none, 4, Place.volcano, 0, null, Shape.giant, Attribute.mecha,
              919, 835, 955, 895, 881, 861,
              new Array(Skill.slash3, Skill.atk10, Skill.agi20, Skill.wis20, Skill.atk20, Skill.ddef20),
              new Array(Skill.slash3, Skill.atk10, Skill.atk20),
              new Array(Skill.slash3, Skill.atk20, Skill.ddef20))
));

Card.addLimitedTypes({
    "30040": new Array(Type.cool, Type.coolr), // Anahita
    "30041": new Array(Type.cool, Type.coolr), // Peri
    "30042": new Array(Type.cool, Type.coolr) // Virtus
});

Card.addNotes({
    // "30014": "HP and WIS not confirmed",        // Lich
    // "30039": "Skills from Jap version, profile missing",       // Thunder God Dongo
    // "30052": "All data from Japanese version",  // Echidna
    // "30071": "Rebirth skill not confirmed",     // Gremory
    // "30077": "Rebirth skill not confirmed",     // Guede
    // "30079": "Rebirth skill not confirmed",     // Andras
    // "30081": "Rebirth skill not confirmed",     // Marduk
    // "30083": "Skillset not confirmed",          // Sai Tai Sai
    // "30084": "Rebirth skill not confirmed",
    // "30085": "All data from Jap version",
    // "30086": "Rebirth skill not confirmed",          // Cybele
    // "30087": "Rebirth skill not confirmed",          // Adad
    // "30088": "Rebirth skill not confirmed",          // Mitra
    // "30089": "Skills not confirmed",                 // Pemphredo
    // "30090": "Skills from Japanese version",         // General Frost
    // "30091": "Skills from Japanese version",         // Malthus
    // "30093": "Rebirth skill from Japanese version",  // Hantu Raya
    // "30094": "Rebirth skill from Japanese version",  // Pantera
    // "30095": "Rebirth skill from Japanese version",  // Sharabha
    // "30097": "Skills from Japanese version",         // Amalthea
    // "30098": "All data from Japanese version",       // 
    // "30099": "All data from Japanese version",       // 
    // "30100": "Skills from Japanese version"          // Mother of Abominations
});

ExCard.addAll(new Array(
/*     new Array("35001", "Grendel", "Born of a line cursed by heaven, this giant's forays on a king's mead hall ended when it lost an arm in the doing.",
              Event.none, ExType.red, 4, Place.plains_night, 0, Shape.giant, Attribute.earth,
              new Array(ExSkill.hp3, ExSkill.hp5, ExSkill.hp7)),
    new Array("35002", "Sandwalker", "",
              Event.none, ExType.red, 4, Place.plains_night, 0, Shape.humanoid, Attribute.earth,
              new Array(ExSkill.earth2, ExSkill.earth4, ExSkill.earth6)),
    new Array("35003", "Sitri", "Darker than darkness itself, this cunning demoness knows all secrets kept, and reveals them at her pleasure.",
              Event.none, ExType.red, 4, Place.plains_night, 0, Shape.female, Attribute.wind,
              new Array(ExSkill.wind2, ExSkill.wind4, ExSkill.wind6)),
    new Array("35004", "Phalaris", "",
              Event.none, ExType.red, 4, Place.plains_night, 0, Shape.wolf, Attribute.mecha,
              new Array(ExSkill.mecha2, ExSkill.mecha4, ExSkill.mecha6)),
    new Array("35005", "Cerpinus", "Foremost among all dargonkin, this heavenly being descended after the fall of civilization to bring order once more.",
              Event.none, ExType.red, 4, Place.plains_night, 0, Shape.female, Attribute.light,
              new Array(ExSkill.light2, ExSkill.light4, ExSkill.light6)),
    new Array("35006", "Beelzebub", "",
              Event.none, ExType.red, 4, Place.plains_night, 0, Shape.humanoid, Attribute.darkness,
              new Array(ExSkill.darkness2, ExSkill.darkness4, ExSkill.darkness6)),
    new Array("35007", "Brynhildr", "The ring of betrothal the dragonslayer gifted this fair shieldmaiden bore a curse that visited upon her a cruel fate.",
              Event.none, ExType.red, 4, Place.plains_night, 0, Shape.female, Attribute.light,
              new Array(ExSkill.wis2, ExSkill.wis4, ExSkill.wis6)),
    new Array("35008", "Zmey Gorynych", "",
              Event.none, ExType.blue, 4, Place.plains_night, 0, Shape.dragon, Attribute.fire,
              new Array(ExSkill.suc_sd3, ExSkill.suc_sd5, ExSkill.suc_sd7)),
    new Array("35009", "Jenn", "Possession by this spirit rots the mind and body, and can be ended only with trances, music, and offerings of blood.",
              Event.none, ExType.red, 4, Place.plains_night, 0, Shape.bird, Attribute.wind,
              new Array(ExSkill.def10, ExSkill.def12, ExSkill.def15)),
    new Array("35010", "Aeacus", "",
              Event.none, ExType.blue, 4, Place.plains_night, 0, Shape.humanoid, Attribute.death,
              new Array(ExSkill.suc_death1, ExSkill.suc_death2, ExSkill.suc_death3)),
    new Array("35011", "Lucifuge Rofocale", "One of eleven who govern in hell, this demon lord controls all wealth in the mortal realm by his master's order.",
              Event.pink_slime, ExType.red, 4, Place.quests, 0, Shape.none, Attribute.darkness,
              new Array(ExSkill.mp5, ExSkill.mp7, ExSkill.mp10)),
    new Array("35012", "Alcyone", "Torn by grief after her lover died upon a stormy sea, this divine daughter was turned to a bird by the pity of the gods.",
              Event.pink_slime, ExType.blue, 4, Place.quests, 0, Shape.none, Attribute.wind,
              new Array(ExSkill.suc_ds2, ExSkill.suc_ds3, ExSkill.suc_ds5)),
    new Array("35013", "Enkidu", "",
              Event.pink_slime, ExType.blue, 4, Place.quests, 0, Shape.wolf, Attribute.lightning,
              new Array(ExSkill.suc_gs2, ExSkill.suc_gs3, ExSkill.suc_gs5)) */
)); 
