/*
 * Card:
 *   ID Name Description Event Border Stars Place Place2 Prototype Shape Attribute HP MP ATK DEF AGI WIS 
 *   Skills Recommends RecommendsRB
 */
Card.addAll(new Array(
    new Array("40001", "Ifrit", "A evil spirit that controls the very fires of hell, mercilessly burning foes to ashes.", 
              Event.none, Border.none, 5, Place.volcano, 0, null, Shape.giant, Attribute.fire,
              1010, 1005, 1080, 1050, 920, 920,
              new Array(Skill.fire3, Skill.fire3, Skill.physical2, Skill.physical3, Skill.fire4, Skill.atk25),
              new Array(Skill.fire3, Skill.physical3, Skill.fire4),
              new Array(Skill.physical3, Skill.fire4, Skill.atk25)),
    new Array("40002", "Leviathan", "An ancient sea dragon and ruler of the oceans that stirs up great waves capable of swallowing creation.", 
              Event.none, Border.none, 5, Place.plains, 0, null, Shape.dragon, Attribute.water,
              1025, 1015, 1050, 1080, 900, 920,
              new Array(Skill.water2, Skill.water3, Skill.physical2, Skill.physical3, Skill.water4, Skill.revival),
              new Array(Skill.water3, Skill.physical3, Skill.water4),
              new Array(Skill.physical3, Skill.water4, Skill.revival)),
    new Array("40003", "Titan", "This being of stone ruled with the deities of eld until their defeat and exile at the hands of the new gods.", 
              Event.none, Border.none, 5, Place.plains, 0, null, Shape.giant, Attribute.earth,
              1050, 1025, 1070, 1060, 910, 910,
              new Array(Skill.physical3, Skill.earth3, Skill.atk20, Skill.def20, Skill.physical4, Skill.atk25),
              new Array(Skill.atk20, Skill.def20, Skill.physical4),
              new Array(Skill.atk20, Skill.physical4, Skill.atk25)),
    new Array("40004", "Lightning Lord", "This supreme ruler over the many gods and spirits of lightning punishes the wicked with thunderbolts.", 
              Event.none, Border.none, 5, Place.volcano, 0, null, Shape.humanoid, Attribute.lightning,
              950, 1002, 1050, 1030, 1070, 950,
              new Array(Skill.lightning2, Skill.lightning3, Skill.wis20, Skill.majorheal, Skill.lightning4, Skill.dwis20),
              new Array(Skill.lightning3, Skill.wis20, Skill.lightning4),
              new Array(Skill.wis20, Skill.lightning4, Skill.dwis20)),
    new Array("40007", "Vampire Matron", "This vampiress ranks high among the undead and is ever attended by a throng of her bastard progeny.", 
              Event.none, Border.none, 5, Place.plains, 0, null, Shape.humanoid, Attribute.death,
              1008, 1007, 980, 960, 1008, 1002,
              new Array(Skill.life, Skill.darkness3, Skill.slash3, Skill.mana, Skill.revival, Skill.agiwis10),
              new Array(Skill.darkness3, Skill.slash3, Skill.revival),
              new Array(Skill.darkness3, Skill.revival, Skill.agiwis10)),
    new Array("40008", "Juggernaut", "Used in battles of high antiquity, this massive machine of war crushes its foes with overwhelming force.", 
              Event.none, Border.none, 5, Place.volcano, 0, null, Shape.wolf, Attribute.mecha,
              850, 868, 1110, 1150, 852, 880,
              new Array(Skill.physical3, Skill.atk20, Skill.def20, Skill.physical4, Skill.ddef20, Skill.qs),
              new Array(Skill.atk20, Skill.physical4, Skill.ddef20),
              new Array(Skill.atk20, Skill.physical4, Skill.qs)),
    new Array("40009", "Dominion", "This angel bears a sceptre of divine authority and seeks to bring all of creation under the rule of heaven.", 
              Event.none, Border.none, 5, Place.volcano, 0, null, Shape.humanoid, Attribute.light,
              920, 1020, 1127, 1068, 1008, 1148,
              new Array(Skill.light3, Skill.majorheal, Skill.atk20, Skill.def20, Skill.light4, Skill.atkwis10),
              new Array(Skill.atk20, Skill.def20, Skill.light4),
              new Array(Skill.atk20, Skill.light4, Skill.atkwis10)),
    new Array("40010", "Mephistopheles", "This demon duke of hell wields great power, but resorts to trickery and guile to corrupt mortal souls.", 
              Event.none, Border.none, 5, Place.volcano, 0, null, Shape.humanoid, Attribute.darkness,
              900, 1138, 940, 950, 976, 1050,
              new Array(Skill.darkness3, Skill.wis20, Skill.slash3, Skill.mana, Skill.darkness4, Skill.agiwis10),
              new Array(Skill.wis20, Skill.slash3, Skill.darkness4),
              new Array(Skill.wis20, Skill.darkness4, Skill.agiwis10)),
    new Array("40011", "Phoenix", "A symbol of immortality and rebirth, this bird immolates every few centuries only to rise from the ashes.", 
              Event.none, Border.none, 5, Place.plains, 0, null, Shape.bird, Attribute.fire,
              952, 934, 980, 1020, 1084, 1016,
              new Array(Skill.revival, Skill.physical2, Skill.fire2, Skill.def20, Skill.fire3, Skill.atkwis10),
              new Array(Skill.revival, Skill.def20, Skill.fire3),
              new Array(Skill.revival, Skill.fire3, Skill.atkwis10)),
    new Array("40012", "Valkyrie", "A beautiful warrior maiden who guides the spirits of those slain in battle to the great hall of the fallen.", 
              Event.none, Border.none, 5, Place.plains, 0, null, Shape.humanoid, Attribute.light,
              912, 1061, 980, 976, 1039, 1077,
              new Array(Skill.slash2, Skill.light3, Skill.atk20, Skill.slash3, Skill.light4, Skill.wis25),
              new Array(Skill.atk20, Skill.slash3, Skill.light4),
              new Array(Skill.slash3, Skill.light4, Skill.wis25)),
    new Array("40013", "Lord of the Inferno", "A primeval god of fire whose netherflames reduce all they touch to ash. - FINAL FANTASY XIV", 
              Event.none, Border.none, 5, Place.invitation, 1, null, Shape.giant, Attribute.fire,
              1030, 1005, 1069, 1051, 957, 946,
              new Array(Skill.fire3, Skill.wis10, Skill.def20, Skill.wis20, Skill.fire4, Skill.atkdef10),
              new Array(Skill.wis10, Skill.wis20, Skill.fire4),
              new Array(Skill.wis10, Skill.wis20, Skill.fire4)),
    new Array("40017", "Apsara", "This water nymph is a shapeshifter of irresistible beauty whose favorite form is the graceful swan.", 
              Event.none, Border.none, 5, Place.plains, 0, null, Shape.humanoid, Attribute.water, 
              1030, 1170, 912, 910, 1062, 1130, 
              new Array(Skill.water1, Skill.water2, Skill.agi20, Skill.dwis20, Skill.water4, Skill.agiwis10),
              new Array(Skill.agi20, Skill.dwis20, Skill.water4),
              new Array(Skill.dwis20, Skill.water4, Skill.agiwis10)),
    new Array("40018", "Stymphalian Bird", "Belonging to the god of war, this bird shreds through armor with its sharp metal feathers and talons.", 
              Event.none, Border.none, 5, Place.snowfield, 0, null, Shape.bird, Attribute.mecha,
              840, 910, 1037, 1004, 1127, 912,
              new Array(Skill.physical2, Skill.ddef20, Skill.physical3, Skill.agi20, Skill.physical4, Skill.qs),
              new Array(Skill.ddef20, Skill.agi20, Skill.physical4),
              new Array(Skill.ddef20, Skill.physical4, Skill.qs)),
    new Array("40019", "Azi Dahaka", "The work of a dark god, this vile dragon has blood which spawns venomous beasts when spilled.", 
              Event.none, Border.none, 5, Place.plains, 0, null, Shape.wolf, Attribute.poison, 
              1200, 1030, 1060, 913, 927, 1080, 
              new Array(Skill.poison2, Skill.poison3, Skill.dagi20, Skill.dwis20, Skill.poison4, Skill.defwis10),
              new Array(Skill.dagi20, Skill.dwis20, Skill.poison4),
              new Array(Skill.dwis20, Skill.poison4, Skill.defwis10)),
    new Array("40020", "Gargantua", "Created by an ancient civilization, this war machine has the power to lay waste to entire armies.", 
              Event.none, Border.none, 5, Place.plains, 0, null, Shape.orbs, Attribute.mecha,
              1210, 914, 1200, 1020, 915, 940,
              new Array(Skill.slash2, Skill.def10, Skill.slash3, Skill.def20, Skill.physical4, Skill.atk25),
              new Array(Skill.def10, Skill.def20, Skill.physical4),
              new Array(Skill.def20, Skill.physical4, Skill.atk25)),
    new Array("40021", "Shiva", "This comely elemental is the queen of ice, and freezes her enemies with the cold she commands.", 
              Event.none, Border.none, 5, Place.snowfield, 0, null, Shape.humanoid, Attribute.water,
              1012, 1183, 1002, 1028, 985, 1090,
              new Array(Skill.water2, Skill.water3, Skill.wis20, Skill.dagi20, Skill.water4, Skill.agiwis10),
              new Array(Skill.wis20, Skill.dagi20, Skill.water4),
              new Array(Skill.wis20, Skill.dagi20, Skill.water4)),
    new Array("40022", "Atlas", "Once servant to the old gods, this mighty being was charged by the new gods to bear up the heavens.", 
              Event.none, Border.none, 5, Place.snowfield, 0, null, Shape.wolf, Attribute.earth,
              1160, 930, 1150, 1090, 913, 911,
              new Array(Skill.physical2, Skill.atk10, Skill.physical3, Skill.atk20, Skill.physical4, Skill.ls),
              new Array(Skill.atk10, Skill.atk20, Skill.physical4),
              new Array(Skill.atk20, Skill.physical4, Skill.ls)),
    new Array("40023", "Raijin", "By beating his mighty drum, this storm god rains down thunder and lightning from the skies.", 
              Event.none, Border.none, 5, Place.snowfield, 0, null, Shape.orbs, Attribute.lightning,
              1070, 980, 1120, 1020, 1030, 1100,
              new Array(Skill.lightning2, Skill.lightning3, Skill.physical2, Skill.physical3, Skill.lightning4, Skill.revival),
              new Array(Skill.lightning3, Skill.physical3, Skill.lightning4),
              new Array(Skill.physical3, Skill.lightning4, Skill.revival)),
    new Array("40024", "Fujin", "This god commands wind and illness, which he visits upon the earth from the great bag upon his back.", 
              Event.none, Border.none, 5, Place.snowfield, 0, null, Shape.orbs, Attribute.wind,
              1010, 1020, 1080, 1030, 1040, 1100,
              new Array(Skill.wind2, Skill.wind3, Skill.dwis20, Skill.ddef20, Skill.physical4, Skill.revival),
              new Array(Skill.dwis20, Skill.ddef20, Skill.physical4),
              new Array(Skill.ddef20, Skill.physical4, Skill.revival)),
    new Array("40025", "Frankenstein", "This abomination was made from the parts of many corpses by a youth obsessed with creating life.", 
              Event.none, Border.none, 5, Place.plains, 0, null, Shape.giant, Attribute.death,
              1130, 911, 1130, 1100, 955, 970,
              new Array(Skill.physical2, Skill.atk20, Skill.wis20, Skill.physical3, Skill.lightning4, Skill.def25),
              new Array(Skill.atk20, Skill.wis20, Skill.physical3),
              new Array(Skill.atk20, Skill.wis20, Skill.physical3)),
    new Array("40030", "Bahamut", "This great wyrm rules the dark dragons, and nothing can withstand the heat of the flames it breathes.", 
              Event.bahamut, Border.none, 5, Place.volcano, 0, null, Shape.orbs, Attribute.darkness,
              1000, 1006, 1111, 954, 999, 1028,
              new Array(Skill.atk20, Skill.physical2, Skill.fire3, Skill.wis20, Skill.darkness4, Skill.atkwis10),
              new Array(Skill.atk20, Skill.wis20, Skill.darkness4),
              new Array(Skill.wis20, Skill.darkness4, Skill.atkwis10)),
    new Array("40037", "Iron Maiden", "Forged by heartless men, this lady of metal is driven to love but doomed to impale any she dare holds.", 
              Event.none, Border.none, 5, Place.invitation, 2, null, Shape.humanoid, Attribute.mecha,
              1058, 988, 1099, 1037, 944, 932,
              new Array(Skill.slash2, Skill.atk20, Skill.slash3, Skill.agi20, Skill.slash4, Skill.atkagi10),
              new Array(Skill.atk20, Skill.agi20, Skill.slash4),
              new Array(Skill.atk20, Skill.slash4, Skill.atkagi10)),
    new Array("40038", "Requiem Banshee", "It is said when a great hero perished, this spirit wept a repose for his soul, moving the hearts of all who heard.", 
              Event.none, Border.none, 5, Place.invitation, 2, "10014", Shape.humanoid, Attribute.death,
              961, 1106, 966, 1001, 1005, 1120,
              new Array(Skill.darkness2, Skill.dwis20, Skill.darkness3, Skill.agi20, Skill.revival, Skill.darkness4),
              new Array(Skill.dwis20, Skill.darkness3, Skill.revival),
              new Array(Skill.dwis20, Skill.revival, Skill.darkness4)),
    new Array("40047", "Sucellus", "This old god of lightning and drink wields in one hand his great hammer, and in the other a draught of wine or ale.", 
              Event.none, Border.none, 5, Place.volcano, 0, null, Shape.humanoid, Attribute.lightning,
              1060, 1072, 1080, 975, 980, 1180,
              new Array(Skill.lightning2, Skill.physical2, Skill.lightning3, Skill.physical3, Skill.lightning4, Skill.atkwis10),
              new Array(Skill.lightning3, Skill.physical3, Skill.lightning4),
              new Array(Skill.physical3, Skill.lightning4, Skill.atkwis10)),
    new Array("40048", "Chariot", "Forged after the war machines of old, this metallic menace charges with the force to reduce all before it to ruin.", 
              Event.none, Border.none, 5, Place.volcano, 0, null, Shape.wolf, Attribute.mecha,
              1080, 935, 1140, 1038, 1105, 880,
              new Array(Skill.physical2, Skill.slash2, Skill.atk20, Skill.agi20, Skill.physical4, Skill.qs),
              new Array(Skill.atk20, Skill.agi20, Skill.physical4),
              new Array(Skill.atk20, Skill.physical4, Skill.qs)),
    new Array("40049", "Ettin", "Able to turn foes to stone, the magic of this two-headed giant and devourer of man is as terrifying as its strength.", 
              Event.none, Border.none, 5, Place.volcano, 0, null, Shape.giant, Attribute.earth,
              1085, 1120, 979, 1109, 927, 1200,
              new Array(Skill.wis10, Skill.earth3, Skill.dwis20, Skill.earth4, Skill.wis20, Skill.agiwis10),
              new Array(Skill.dwis20, Skill.earth4, Skill.wis20),
              new Array(Skill.earth4, Skill.wis20, Skill.agiwis10)),
    new Array("40050", "Agni", "This god of fire in all its forms is at once the sun in the heavens, lightning in the skies, and flames upon earth.", 
              Event.none, Border.none, 5, Place.volcano, 0, null, Shape.humanoid, Attribute.fire,
              1045, 1168, 1030, 1000, 1024, 1180,
              new Array(Skill.fire3, Skill.physical2, Skill.def20, Skill.physical3, Skill.fire4, Skill.sd),
              new Array(Skill.def20, Skill.physical3, Skill.fire4),
              new Array(Skill.def20, Skill.fire4, Skill.sd)),
    new Array("40052", "Sphinx Empress", "The empress leads those sacred beasts which guard royalty, and appears every bit as regal as the title she bears.", 
              Event.none, Border.none, 5, Place.desert, 0, null, Shape.wolf, Attribute.light,
              1080, 1044, 1130, 985, 1162, 1159,
              new Array(Skill.qs, Skill.atk20, Skill.dwis20, Skill.physical3, Skill.light3, Skill.wis20),
              new Array(Skill.qs, Skill.dwis20, Skill.light3),
              new Array(Skill.qs, Skill.light3, Skill.wis20)),
    new Array("40053", "Nuada", "Lessened an arm in battle, this king among gods was forged a new one of silver, that he might maintain his throne.", 
              Event.none, Border.none, 5, Place.desert, 0, null, Shape.humanoid, Attribute.mecha,
              1032, 977, 1210, 1103, 1003, 975,
              new Array(Skill.ls, Skill.atk20, Skill.physical3, Skill.slash3, Skill.physical4, Skill.atkdef10),
              new Array(Skill.ls, Skill.atk20, Skill.physical4),
              new Array(Skill.ls, Skill.atk20, Skill.physical4)),
    new Array("40054", "Serenade Banshee", "On the death of a saint, this spirit's cries turned to a path, and her tears to lights. By them, the soul was seen safe across.", 
              Event.none, Border.none, 5, Place.desert, 0, "10014", Shape.female, Attribute.death,
              991, 1080, 959, 1001, 1039, 1220,
              new Array(Skill.death1, Skill.death2, Skill.wis20, Skill.death3, Skill.death4, Skill.defagi10),
              new Array(Skill.wis20, Skill.death3, Skill.death4),
              new Array(Skill.wis20, Skill.death4, Skill.defagi10)),
    new Array("40055", "Mictlantecuhtli", "This undead king rules in the lowest hell, imbibing the sacrificial blood offered him by his cannabilistic worshippers.", 
              Event.none, Border.none, 5, Place.desert, 0, null, Shape.orbs, Attribute.death,
              1005, 1242, 910, 1059, 955, 1079,
              new Array(Skill.sd, Skill.wis10, Skill.poison3, Skill.poison4, Skill.wis20, Skill.defwis10),
              new Array(Skill.wis10, Skill.poison4, Skill.wis20),
              new Array(Skill.poison4, Skill.wis20, Skill.defwis10)),
    new Array("40056", "Behemoth", "Such is the appetite of this monstrosity that it devours the grasses of a thousand mountainsides in a single day.", 
              Event.none, Border.none, 5, Place.desert, 0, null, Shape.beast, Attribute.earth,
              1149, 940, 1163, 1215, 890, 978,
              new Array(Skill.ls, Skill.earth2, Skill.def20, Skill.physical3, Skill.earth3, Skill.atkdef10),
              new Array(Skill.ls, Skill.def20, Skill.physical3),
              new Array(Skill.ls, Skill.physical3, Skill.atkdef10)),
    new Array("40334", "Dark Divinity", "It is whispered this ancient primal roams the Black Shroud astride his steed Sleipnir, seeking worthy foes.", 
              Event.ff14, Border.none, 5, Place.plains, 0, null, Shape.wolf, Attribute.darkness, 
              952, 992, 1060, 1020, 1008, 1016,
              new Array(Skill.revival, Skill.slash2, Skill.slash3, Skill.atk20, Skill.slash4, Skill.agi25),
              new Array(Skill.revival, Skill.atk20, Skill.slash4),
              new Array(Skill.revival, Skill.atk20, Skill.slash4)),
    new Array("40335", "Lord of Crags", "The kobolds of O'Ghomoro worship this fierce god of stone, whose Earthen Fury causes the very ground to tremor.", 
              Event.ff14, Border.none, 5, Place.plains, 0, null, Shape.humanoid, Attribute.earth, 
              1130, 1025, 1070, 1060, 960, 940,
              new Array(Skill.def20, Skill.physical2, Skill.physical3, Skill.ddef20, Skill.physical4, Skill.def25),
              new Array(Skill.def20, Skill.ddef20, Skill.physical4),
              new Array(Skill.ddef20, Skill.physical4, Skill.def25)),
    new Array("40336", "Lord of the Whorl", "Called forth by a fell Sahagin ritual, this serpentine god lurks in the dark ocean depths, threatening to swallow all.", 
              Event.ff14, Border.none, 5, Place.plains, 0, null, Shape.dragon, Attribute.water, 
              1025, 1015, 1050, 1080, 900, 920,
              new Array(Skill.water2, Skill.water3, Skill.physical3, Skill.physical4, Skill.water4),
              new Array(Skill.physical3, Skill.physical4, Skill.water4),
              new Array(Skill.physical3, Skill.physical4, Skill.water4)),
    new Array("40337", "Primal Bahamut", "", 
              Event.ff14, Border.none, 5, Place.plains, 0, null, Shape.bird, Attribute.darkness, 
              1080, 1032, 940, 978, 1025, 1100,
              new Array(Skill.wis20, Skill.darkness2, Skill.darkness3, Skill.agi20, Skill.darkness4, Skill.agiwis10),
              new Array(Skill.wis20, Skill.agi20, Skill.darkness4),
              new Array(Skill.wis20, Skill.darkness4, Skill.agiwis10)),
    new Array("40338", "Lady of the Vortex", "This matron deity of the lxal is gripped by an unquellable madness of mind and an unquenchable thirst for blood.", 
              Event.ff14, Border.none, 5, Place.plains, 0, null, Shape.female, Attribute.wind, 
              900, 1002, 1060, 1030, 1100, 1060,
              new Array(Skill.ddef20, Skill.wind3, Skill.slash3, Skill.dwis20, Skill.wind4, Skill.wis25),
              new Array(Skill.ddef20, Skill.dwis20, Skill.wind4),
              new Array(Skill.dwis20, Skill.wind4, Skill.wis25)),
	new Array("44006", "Christmas Banshee", "On the night before Christmas, the tears of this lamenting spirit take on the brilliance of stars and fill the firmament.", 
              Event.holidayhunt, Border.none, 5, Place.snowfield, 0, null, Shape.humanoid, Attribute.death, 
              1010, 1100, 930, 1001, 1040, 1200,
              new Array(Skill.death2, Skill.darkness3, Skill.wis20, Skill.death4, Skill.darkness4, Skill.defagi10),
              new Array(Skill.wis20, Skill.death4, Skill.darkness4),
              new Array(Skill.wis20, Skill.death4, Skill.defagi10)),
	new Array("44005", "Jolly Old Azi Dahaka", "This fiendish dragon turned good now toils to spread holiday cheer, using magic to bring gifts and smiles to all.", 
              Event.holidayhunt, Border.none, 5, Place.snowfield, 0, null, Shape.wolf, Attribute.poison, 
              1180, 1030, 1080, 913, 1010, 1220,
              new Array(Skill.ls, Skill.light3, Skill.dwis20, Skill.light4, Skill.wis20, Skill.atkwis10),
              new Array(Skill.ls, Skill.light4, Skill.wis20),
              new Array(Skill.ls, Skill.light4, Skill.wis20)),
	new Array("44004", "Yuletide Lich", "This powerful lich knows who has been naughty and who has been nice, and on Christmas Eve the chimney of no home can deny her.", 
              Event.holidayhunt, Border.none, 5, Place.snowfield, 0, null, Shape.orbs, Attribute.death, 
              1027, 1000, 959, 1001, 1040, 1080,
              new Array(Skill.life, Skill.dwis20, Skill.darkness4, Skill.light4, Skill.revival, Skill.agiwis10),
              new Array(Skill.dwis20, Skill.darkness4, Skill.revival),
              new Array(Skill.darkness4, Skill.revival, Skill.agiwis10)),
	new Array("40090", "Hoarfrost Phoenix", "Aged an eternity, the body of this undying bird sprouts deadly feathers of winter ice that cannot be broken.", 
              Event.none, Border.none, 5, Place.snowfield, 0, null, Shape.bird, Attribute.water, 
              1027, 993, 993, 1053, 1140, 1074,
              new Array(Skill.revival, Skill.water2, Skill.qs, Skill.physical3, Skill.water3, Skill.agiwis10),
              new Array(Skill.revival, Skill.qs, Skill.water3),
              new Array(Skill.revival, Skill.qs, Skill.water3)),
	new Array("40091", "Crocell", "This dark angel has the power to warm waters, and bestows great knowledge upon any who summons her.", 
              Event.none, Border.none, 5, Place.snowfield, 0, null, Shape.female, Attribute.water, 
              995, 1440, 992, 950, 992, 1095,
              new Array(Skill.slash2, Skill.dwis20, Skill.death3, Skill.wis20, Skill.sd, Skill.agiwis10),
              new Array(Skill.dwis20, Skill.death3, Skill.wis20),
              new Array(Skill.dwis20, Skill.death3, Skill.wis20)),
	new Array("40092", "Thor", "Unmatched in power, this noble god of lightning fells all who oppose him with a single blow of his mighty hammer.", 
              Event.none, Border.none, 5, Place.snowfield, 0, null, Shape.giant, Attribute.lightning, 
              1200, 1007, 1193, 960, 993, 1047,
              new Array(Skill.lightning3, Skill.def20, Skill.physical4, Skill.atk20, Skill.ls, Skill.atkdef10),
              new Array(Skill.physical4, Skill.atk20, Skill.ls),
              new Array(Skill.physical4, Skill.atk20, Skill.ls)),
	new Array("40093", "Morrighan", "The war cry of this goddess of strife sets battlegrounds ablaze and stirs the blood frenzy in the hearts of warriors.", 
              Event.none, Border.none, 5, Place.snowfield, 0, null, Shape.female, Attribute.death, 
              1070, 1012, 1180, 1065, 1120, 1090,
              new Array(Skill.darkness3, Skill.slash3, Skill.atk20, Skill.slash4, Skill.qs, Skill.ls),
              new Array(Skill.atk20, Skill.slash4, Skill.qs),
              new Array(Skill.slash4, Skill.qs, Skill.ls)),
	new Array("40085", "Hellfire Vimana", "Crafted in ages long past, this armored airship casts a shadow of terror as it soars, scorching both earth and sky.", 
              Event.none, Border.none, 5, Place.fp, 0, null, Shape.none, Attribute.none, 
              1320, 1520, 937, 1200, 980, 1115,
              new Array(Skill.fire4, Skill.def20, Skill.wis20, Skill.light4, Skill.sd),
              new Array(Skill.fire4, Skill.wis20, Skill.sd),
              new Array(Skill.fire4, Skill.wis20, Skill.sd)),
	new Array("40078", "Gilgamesh", "Half man and half god, the majesty of this fierce and ancient king is such that even feral lions bend to his will.", 
              Event.gilgamesh, Border.none, 5, Place.volcano, 0, null, Shape.giant, Attribute.lightning, 
              1203, 999, 1040, 1078, 940, 1120,
              new Array(Skill.ls, Skill.lightning3, Skill.wis20, Skill.dagi20, Skill.lightning4, Skill.agi25),
              new Array(Skill.ls, Skill.wis20, Skill.lightning4),
              new Array(Skill.ls, Skill.wis20, Skill.lightning4)),
	new Array("40444", "Hecatoncheir (FFXIII)", "", 
              Event.ff13, Border.none, 5, Place.desert, 0, null, Shape.orbs, Attribute.earth, 
              1200, 977, 1200, 1050, 1020, 974,
              new Array(Skill.ls, Skill.atk20, Skill.def20, Skill.physical3, Skill.physical4, Skill.atkdef10),
              new Array(Skill.ls, Skill.atk20, Skill.physical4),
              new Array(Skill.ls, Skill.atk20, Skill.physical4)),
	new Array("40429", "Brynhildr (FFXIII)", "", 
              Event.ff13, Border.none, 5, Place.desert, 0, null, Shape.giant, Attribute.fire, 
              985, 1520, 960, 990, 1030, 1088,
              new Array(Skill.sd, Skill.wis10, Skill.fire3, Skill.fire4, Skill.wis20),
              new Array(Skill.sd, Skill.fire4, Skill.wis20),
              new Array(Skill.sd, Skill.fire4, Skill.wis20)),
	new Array("44002", "Shiva (FFXIII)", "", 
              Event.ff13, Border.none, 5, Place.desert, 0, null, Shape.orbs, Attribute.water, 
              1000, 988, 1160, 1037, 1060, 1140,
              new Array(Skill.physical3, Skill.atk20, Skill.wis20, Skill.physical4, Skill.death4, Skill.defagi10),
              new Array(Skill.atk20, Skill.physical4, Skill.death4),
              new Array(Skill.atk20, Skill.physical4, Skill.death4)),
	new Array("44003", "Bahamut (FFXIII)", "", 
              Event.ff13, Border.none, 5, Place.desert, 0, null, Shape.dragon, Attribute.darkness, 
              1030, 1400, 1120, 1000, 1040, 945,
              new Array(Skill.sd, Skill.atk20, Skill.slash3, Skill.def20, Skill.slash4, Skill.atkdef10),
              new Array(Skill.sd, Skill.atk20, Skill.slash4),
              new Array(Skill.sd, Skill.atk20, Skill.slash4)),
	new Array("40446", "Cactuar King (FFXIII)", "", 
              Event.ff13, Border.none, 5, Place.desert, 0, null, Shape.cactus, Attribute.earth, 
              400, 960, 940, 1040, 1120, 1110,
              new Array(Skill.death2, Skill.death3, Skill.agi20, Skill.revival, Skill.slash4, Skill.agiwis10),
              new Array(Skill.death3, Skill.agi20, Skill.revival),
              new Array(Skill.death3, Skill.agiwis10, Skill.revival)),
	new Array("44001", "Chocobo Eater (FFXIII)", "", 
              Event.ff13, Border.none, 5, Place.desert, 0, null, Shape.orbs, Attribute.earth, 
              1220, 1000, 1120, 980, 1120, 800,
              new Array(Skill.slash2, Skill.datk20, Skill.slash3, Skill.atk20, Skill.slash4, Skill.atkdef10),
              new Array(Skill.datk20, Skill.atk20, Skill.slash4),
              new Array(Skill.atk20, Skill.slash4, Skill.atkdef10)),
	new Array("40445", "Odin (FFXIII)", "", 
              Event.ff13, Border.none, 5, Place.desert, 0, null, Shape.wolf, Attribute.lightning, 
              1040, 1060, 1120, 985, 1170, 1200,
              new Array(Skill.qs, Skill.slash3, Skill.agi20, Skill.wis20, Skill.lightning4, Skill.agiwis10),
              new Array(Skill.qs, Skill.wis20, Skill.lightning4),
              new Array(Skill.qs, Skill.wis20, Skill.lightning4)),
	new Array("45000", "Deadman Titan", "A vile scourge tore this fallen god from death's embrace, and now drives him to render all life as unliving as he.", 
              Event.deadman, Border.none, 5, Place.deadman, 0, null, Shape.giant, Attribute.death, 
              920, 1080, 910, 950, 940, 1040,
              new Array(Skill.darkness2, Skill.ddef20, Skill.dwis20, Skill.darkness3, Skill.darkness4, Skill.sd),
              new Array(Skill.ddef20, Skill.dwis20, Skill.darkness4),
              new Array(Skill.dwis20, Skill.darkness4, Skill.sd)),
	new Array("40135", "Pandora", "It was when this first woman succumbed to her curiosity that the ills and evils of the world were unleashed.", 
              Event.none, Border.none, 5, Place.desert, 0, null, Shape.orbs, Attribute.light,
              990, 1600, 996, 940, 1040, 1088,
              new Array(Skill.sd, Skill.ddef20, Skill.datk20, Skill.dwis20, Skill.light4, Skill.death4),
              new Array(Skill.sd, Skill.dwis20, Skill.light4),
              new Array(Skill.sd, Skill.dwis20, Skill.death4)),
	new Array("40136", "Anubis", "This jackal-headed god keeps the sacred scales which weigh the hearts of the dead against the feather of truth.", 
              Event.none, Border.none, 5, Place.desert, 0, null, Shape.humanoid, Attribute.death,
              1382, 1060, 1070, 1093, 996, 1033,
              new Array(Skill.darkness3, Skill.atk20, Skill.slash3, Skill.darkness4, Skill.atk25, Skill.agiwis10),
              new Array(Skill.atk20, Skill.slash3, Skill.atk25),
              new Array(Skill.atk20, Skill.slash3, Skill.atk25)),
	new Array("40137", "Kali", "The fury of this tantric goddess of death and slaughter is feared even by demons in the deepest recesses of hell.", 
              Event.none, Border.none, 5, Place.desert, 0, null, Shape.female, Attribute.darkness,
              1220, 1060, 1120, 1080, 1120, 1160,
              new Array(Skill.slash3, Skill.ddef20, Skill.darkness3, Skill.dwis20, Skill.darkness4, Skill.slash4),
              new Array(Skill.dwis20, Skill.ddef20, Skill.darkness4),
              new Array(Skill.dwis20, Skill.ddef20, Skill.darkness4)),
	new Array("40138", "Marchosias", "Ere an angel of the order of dominions, this marquis of hell now commands the strength of thirty demon legions.", 
              Event.none, Border.none, 5, Place.desert, 0, null, Shape.wolf, Attribute.mecha,
              1200, 1057, 1220, 1000, 1180, 1001,
              new Array(Skill.slash3, Skill.fire3, Skill.atkagi10, Skill.qs, Skill.slash4, Skill.atkdef10),
              new Array(Skill.qs, Skill.slash4, Skill.atkagi10),
              new Array(Skill.qs, Skill.slash4, Skill.atkagi10)),
	new Array("40143", "Ungur", "Known as the rainbow serpent, this primordial being first shaped the world and birthed hosts of its myraid spirits.", 
              Event.none, Border.none, 5, Place.ocean, 0, null, Shape.serpent, Attribute.light,
              1250, 1080, 1050, 1150, 955, 1150,
              new Array(Skill.ep, Skill.heal, Skill.light3, Skill.wis20, Skill.light4, Skill.wis25),
              new Array(Skill.ep, Skill.wis20, Skill.light4),
              new Array(Skill.wis20, Skill.wis25, Skill.light4)),
	new Array("40144", "Cthulhu", "Shadowy chants seek to rouse this god from its slumber, Ph'nglui mglw'nafh Cthulhu R'lyeh wgah'nagl fhtagn.", 
              Event.none, Border.none, 5, Place.ocean, 0, null, Shape.shark, Attribute.death,
              1100, 1120, 1280, 1060, 1100, 1280,
              new Array(Skill.ep, Skill.physical3, Skill.darkness4, Skill.def20, Skill.physical4, Skill.atkwis10),
              new Array(Skill.ep, Skill.darkness4, Skill.physical4),
              new Array(Skill.ep, Skill.atkwis10, Skill.physical4)),
	new Array("40145", "Abaddon", "With his army if locusts, this lord of he'll revels in unleashing protracted suffering and death upon the world.", 
              Event.none, Border.none, 5, Place.ocean, 0, null, Shape.orbs, Attribute.poison,
              980, 1272, 1020, 1160, 1020, 1200,
              new Array(Skill.sap, Skill.darkness3, Skill.def25, Skill.darkness4, Skill.poison4, Skill.defwis10),
              new Array(Skill.sap, Skill.def25, Skill.poison4),
              new Array(Skill.sap, Skill.poison4, Skill.defwis10)),
	new Array("40146", "Lilith", "This fiendish vixen is wife to a demon king, to whom shee bears a hunbred vile spawn with every turn of the sun.", 
              Event.none, Border.none, 5, Place.ocean, 0, null, Shape.mermaid, Attribute.darkness,
              1010, 1100, 1015, 983, 1130, 1220,
              new Array(Skill.ds, Skill.darkness3, Skill.wis20, Skill.agi20, Skill.darkness4, Skill.agiwis10),
              new Array(Skill.ds, Skill.darkness4, Skill.wis20),
              new Array(Skill.ds, Skill.darkness4, Skill.wis20)),
	new Array("40147", "Poseidon", "When mortals spurn the seas, this vengeful ocean god causes the water to surge and swell and drown the land.", 
              Event.none, Border.none, 5, Place.ocean, 0, null, Shape.merman, Attribute.mecha,
              1325, 1003, 1160, 1100, 1004, 1047,
              new Array(Skill.gs, Skill.water3, Skill.def20, Skill.physical3, Skill.wis20, Skill.defwis10),
              new Array(Skill.gs, Skill.water3, Skill.wis20),
              new Array(Skill.gs, Skill.water3, Skill.wis20)),
	new Array("40159", "Artemis", "As goddess of the hunt and mistress of the wild, the arrows lossed from the bow of this divine protector never stray.", 
              Event.none, Border.none, 5, Place.invitation, 3, null, Shape.female, Attribute.light,
              990, 1200, 1060, 1120, 1040, 1120,
              new Array(Skill.sap, Skill.agi10, Skill.slash3, Skill.light4, Skill.slash4, Skill.atkagi10),
              new Array(Skill.sap, Skill.light4, Skill.slash4),
              new Array(Skill.sap, Skill.slash4, Skill.atkagi10)),
	new Array("40160", "Idun", "Among the bounty of this spring goddess are golden apples which bear the gift of eternal youth to the gods.", 
              Event.none, Border.none, 5, Place.invitation, 3, null, Shape.female, Attribute.earth,
              1020, 1080, 973, 1055, 980, 1080,
              new Array(Skill.wis10, Skill.earth3, Skill.earth4, Skill.wis20, Skill.water4, Skill.defwis10),
              new Array(Skill.wis10, Skill.wis20, Skill.water4),
              new Array(Skill.wis20, Skill.water4, Skill.defwis10)),

			//Begin Bordered
    new Array("40015", "Almighty Leviathan", "Spawned from an ocean abyss, this divine serpent rules over the sealords with powers nigh unrivaled.", 
              Event.none, Border.almighty, 5, Place.coliseum, 1, "40002", Shape.dragon, Attribute.water,
              1075, 1065, 1102, 1134, 935, 966,
              new Array(Skill.revival, Skill.water3, Skill.physical2, Skill.physical3, Skill.water4),
              new Array(Skill.revival, Skill.physical3, Skill.water4),
              new Array(Skill.revival, Skill.physical3, Skill.water4)),
    new Array("40059", "Mighty Leviathan", "This serpent deity among the sealords has grown ever more powerful over the countless ages of its life.", 
              Event.none, Border.mighty, 5, Place.coliseum, 1, "40002", Shape.dragon, Attribute.water,
              1025, 1015, 1050, 1080, 900, 920,
              new Array(Skill.water2, Skill.water3, Skill.physical2, Skill.physical3, Skill.water4),
              new Array(Skill.physical3, Skill.physical4, Skill.water4),
              new Array(Skill.physical3, Skill.physical4, Skill.water4)),
    new Array("40016", "Almighty Titan", "The destructive power and vitality of this earthen deity are unmatched among even the ancient gods.", 
              Event.none, Border.almighty, 5, Place.coliseum, 2, "40003", Shape.giant, Attribute.earth,
              1400, 1025, 1070, 1060, 910, 910,
              new Array(Skill.physical3, Skill.earth3, Skill.atk20, Skill.def20, Skill.physical4),
              new Array(Skill.atk20, Skill.def20, Skill.physical4),
              new Array(Skill.atk20, Skill.def20, Skill.physical4)),
	new Array("40062", "Mighty Titan", "This imposing god hails from an ancient line of divinity, and boasts both great size and untold strength.", 
              Event.none, Border.mighty, 5, Place.coliseum, 2, "40003", Shape.giant, Attribute.earth,
              1200, 1025, 1070, 1060, 910, 910,
              new Array(Skill.physical3, Skill.earth3, Skill.atk20, Skill.def20, Skill.physical4),
              new Array(Skill.atk20, Skill.def20, Skill.physical4),
              new Array(Skill.atk20, Skill.def20, Skill.physical4)),
    new Array("40028", "Almighty Ifrit", "This evil fire deity gained great power and an eternal form after being touched by the flames of hell.", 
              Event.none, Border.almighty, 5, Place.coliseum, 3, "40001", Shape.giant, Attribute.fire,
              1090, 1055, 1000, 1102, 966, 1080,
              new Array(Skill.fire2, Skill.fire3, Skill.wis20, Skill.physical3, Skill.fire4),
              new Array(Skill.fire3, Skill.wis20, Skill.fire4),
              new Array(Skill.fire3, Skill.wis20, Skill.fire4)),
    new Array("40029", "Mighty Ifrit", "After imbibing flames from deep within the earth's bowels, this fire god's powers burned ever stronger.", 
              Event.none, Border.mighty, 5, Place.coliseum, 3, "40001", Shape.giant, Attribute.fire,
              1040, 1005, 920, 1050, 920, 1020,
              new Array(Skill.fire2, Skill.fire3, Skill.wis20, Skill.physical3, Skill.fire4),
              new Array(Skill.fire3, Skill.wis20, Skill.fire4),
              new Array(Skill.fire3, Skill.wis20, Skill.fire4)),
	new Array("40039", "Almighty Valkyrie", "With great favor of the gods this valiant warrior maiden soars over battlefields, turning the tides of war.", 
              Event.none, Border.almighty, 5, Place.coliseum,4 , "40010", Shape.humanoid, Attribute.light,
              957, 1114, 1029, 1024, 1090, 1130,
              new Array(Skill.wis20, Skill.light3, Skill.atk20, Skill.slash3, Skill.light4),
              new Array(Skill.wis20, Skill.atk20, Skill.light4),
              new Array(Skill.wis20, Skill.atk20, Skill.light4)),
    new Array("40040", "Mighty Valkyrie", "Guide of valiant souls and scourge of battle, this maiden warrior summons forth powerful magic at will.", 
              Event.none, Border.mighty, 5, Place.coliseum, 4, "40010", Shape.humanoid, Attribute.light,
              930, 1082, 999, 995, 1059, 1098,
              new Array(Skill.wis20, Skill.light3, Skill.atk20, Skill.slash3, Skill.light4),
              new Array(Skill.wis20, Skill.atk20, Skill.light4),
              new Array(Skill.wis20, Skill.atk20, Skill.light4)),
    new Array("40033", "Almighty Mephistopheles", "This beguiling devil grows in power and revels in dark delight with the demise of each tempted soul he claims.", 
              Event.none, Border.almighty, 5, Place.coliseum, 5, "40008", Shape.humanoid, Attribute.darkness,
              945, 1194, 987, 997, 1024, 1102,
              new Array(Skill.agi20, Skill.darkness3, Skill.wis20, Skill.slash3, Skill.darkness4),
              new Array(Skill.agi20, Skill.wis20, Skill.darkness4),
              new Array(Skill.agi20, Skill.wis20, Skill.darkness4)),
    new Array("40034", "Mighty Mephistopheles", "This devil tempts and corrupts the noble souls of man, relishing in the fall of mortals brought about by their own free will.", 
              Event.none, Border.mighty, 5, Place.coliseum, 5, "40008", Shape.humanoid, Attribute.darkness,
              918, 1160, 958, 969, 995, 1071,
              new Array(Skill.agi20, Skill.darkness3, Skill.wis20, Skill.slash3, Skill.darkness4),
              new Array(Skill.agi20, Skill.wis20, Skill.darkness4),
              new Array(Skill.agi20, Skill.wis20, Skill.darkness4)),
	new Array("40031", "Almighty Phoenix", "The torrid flames from which this eternal bird was spawned never die, but live on, burning within its wings and breast.", 
              Event.none, Border.almighty, 5, Place.coliseum, 6, "40009", Shape.bird, Attribute.fire,
              971, 952, 999, 1040, 1105, 1036,
              new Array(Skill.revival, Skill.physical2, Skill.atk20, Skill.def20, Skill.fire4),
              new Array(Skill.revival, Skill.atk20, Skill.fire4),
              new Array(Skill.revival, Skill.atk20, Skill.fire4)),
    new Array("40032", "Mighty Phoenix", "This sacred bird of fire has seen an eternity pass, dying from a fire that burns within only to be reborn from the ash of itself.", 
              Event.none, Border.mighty, 5, Place.coliseum, 6, "40009", Shape.bird, Attribute.fire,
              952, 934, 980, 1020, 1084, 1016,
              new Array(Skill.revival, Skill.physical2, Skill.fire2, Skill.def20, Skill.fire4),
              new Array(Skill.revival, Skill.def20, Skill.fire4),
              new Array(Skill.revival, Skill.def20, Skill.fire4)),
    new Array("40377", "Almighty Lord of Crags", "The kobolds of O'Ghomoro worship this fierce god of stone, whose Earthen Fury causes the very ground to tremor.", 
              Event.none, Border.almighty, 5, Place.coliseum, 7, "40034", Shape.humanoid, Attribute.earth,
              1320, 1025, 1070, 1280, 960, 940,
              new Array(Skill.def20, Skill.physical2, Skill.physical3, Skill.ddef20, Skill.physical4),
              new Array(Skill.def20, Skill.ddef20, Skill.physical4),
              new Array(Skill.def20, Skill.ddef20, Skill.physical4)),
    new Array("40378", "Mighty Lord of Crags", "The kobolds of O'Ghomoro worship this fierce god of stone, whose Earthen Fury causes the very ground to tremor.", 
              Event.none, Border.mighty, 5, Place.coliseum, 7, "40034", Shape.humanoid, Attribute.earth,
              1160, 1025, 1070, 1200, 960, 940,
              new Array(Skill.def20, Skill.physical2, Skill.physical3, Skill.ddef20, Skill.physical4),
              new Array(Skill.def20, Skill.ddef20, Skill.physical4),
              new Array(Skill.def20, Skill.ddef20, Skill.physical4)),
    new Array("40383", "Almighty Primal Bahamut", "Descended from Dalamud, this ancient primal birthed the Seventh Umbral Era, laying Eorzea to ash with its Megaflare.", 
              Event.none, Border.almighty, 5, Place.coliseum, 7, "40036", Shape.bird, Attribute.darkness,
              1080, 1050, 1100, 1030, 1025, 1100,
              new Array(Skill.atk20, Skill.physical2, Skill.physical4, Skill.wis20, Skill.darkness4),
              new Array(Skill.atk20, Skill.wis20, Skill.darkness4),
              new Array(Skill.atk20, Skill.wis20, Skill.darkness4)),
    new Array("40384", "Mighty Primal Bahamut", "Descended from Dalamud, this ancient primal birthed the Seventh Umbral Era, laying Eorzea to ash with its Megaflare.", 
              Event.none, Border.mighty, 5, Place.coliseum, 7, "40036", Shape.bird, Attribute.darkness,
              1080, 1040, 1025, 1040, 978, 1060,
              new Array(Skill.atk20, Skill.physical2, Skill.physical4, Skill.wis20, Skill.darkness4),
              new Array(Skill.atk20, Skill.wis20, Skill.darkness4),
              new Array(Skill.atk20, Skill.wis20, Skill.darkness4)),
    new Array("40374", "Almighty Dark Divinity", "It is whispered this ancient primal roams the Black Shroud astride his steed Sleipnir, seeking worthy foes.", 
              Event.none, Border.almighty, 5, Place.coliseum, 8, "40033", Shape.wolf, Attribute.darkness,
              1000, 1030, 1060, 1050, 1040, 1060,
              new Array(Skill.revival, Skill.wis20, Skill.darkness4, Skill.atk20, Skill.slash4),
              new Array(Skill.revival, Skill.atk20, Skill.slash4),
              new Array(Skill.revival, Skill.atk20, Skill.slash4)),
    new Array("40375", "Mighty Dark Divinity", "It is whispered this ancient primal roams the Black Shroud astride his steed Sleipnir, seeking worthy foes.", 
              Event.none, Border.mighty, 5, Place.coliseum, 8, "40033", Shape.wolf, Attribute.darkness,
              952, 992, 1060, 1020, 1008, 1060,
              new Array(Skill.revival, Skill.wis20, Skill.darkness4, Skill.atk20, Skill.slash4),
              new Array(Skill.revival, Skill.atk20, Skill.slash4),
              new Array(Skill.revival, Skill.atk20, Skill.slash4)),
    new Array("40386", "Almighty Lady of the Vortex", "This matron deity of the lxal is gripped by an unquellable madness of mind and an unquenchable thirst for blood.", 
              Event.none, Border.almighty, 5, Place.coliseum, 8, "40037", Shape.female, Attribute.wind,
              900, 1002, 1120, 1030, 1200, 1000,
              new Array(Skill.ddef20, Skill.wind3, Skill.slash4, Skill.dwis20, Skill.slash4),
              new Array(Skill.ddef20, Skill.dwis20, Skill.slash4),
              new Array(Skill.ddef20, Skill.dwis20, Skill.slash4)),
    new Array("40387", "Mighty Lady of the Vortex", "This matron deity of the lxal is gripped by an unquellable madness of mind and an unquenchable thirst for blood.", 
              Event.none, Border.mighty, 5, Place.coliseum, 8, "40037", Shape.female, Attribute.wind,
              900, 1002, 1080, 1030, 1140, 1000,
              new Array(Skill.ddef20, Skill.wind3, Skill.slash4, Skill.dwis20, Skill.slash4),
              new Array(Skill.ddef20, Skill.dwis20, Skill.slash4),
              new Array(Skill.ddef20, Skill.dwis20, Skill.slash4)),
	new Array("40057", "Almighty Atlas", "The sorcery and strength of this being alone nearly proved the end of the new gods when they dared to wage war upon the old.", 
              Event.none, Border.almighty, 5, Place.coliseum, 9, "40013", Shape.wolf, Attribute.earth,
              1160, 1040, 1150, 1090, 913, 1250,
              new Array(Skill.physical2, Skill.physical3, Skill.atk20, Skill.physical4, Skill.earth4),
              new Array(Skill.atk20, Skill.physical4, Skill.earth4),
              new Array(Skill.atk20, Skill.physical4, Skill.earth4)),
    new Array("40058", "Mighty Atlas", "Beyond his terrifying strength, this valorous and stalwart servant of the old gods also possesses an ancient wisdom.", 
              Event.none, Border.mighty, 5, Place.coliseum, 9, "40013", Shape.wolf, Attribute.earth,
              1160, 1040, 1150, 1090, 913, 1100,
              new Array(Skill.physical2, Skill.physical3, Skill.atk20, Skill.physical4, Skill.earth4),
              new Array(Skill.atk20, Skill.physical4, Skill.earth4),
              new Array(Skill.atk20, Skill.physical4, Skill.earth4)),
	new Array("40139", "Almighty Lightning Lord", "The deadly levinbolts hurled by this lord supreme of the thirty-six lightning spirits always find their target true.", 
              Event.none, Border.almighty, 5, Place.coliseum, 9, "40004", Shape.humanoid, Attribute.lightning,
              1060, 1002, 1050, 1030, 1070, 1050,
              new Array(Skill.lightning2, Skill.lightning3, Skill.wis20, Skill.dwis20, Skill.lightning4),
              new Array(Skill.wis20, Skill.dwis20, Skill.lightning4),
              new Array(Skill.wis20, Skill.dwis20, Skill.lightning4)),
	new Array("40140", "Mighty Lightning Lord", "Wrathful yet merciful, this deity exacts divine vengeance with bolts of lightning and frees the damned from hell's terror.", 
              Event.none, Border.mighty, 5, Place.coliseum, 9, "40004", Shape.humanoid, Attribute.lightning,
              1020, 1002, 1000, 1030, 1070, 1000,
              new Array(Skill.lightning2, Skill.lightning3, Skill.wis20, Skill.dwis20, Skill.lightning4),
              new Array(Skill.wis20, Skill.dwis20, Skill.lightning4),
              new Array(Skill.wis20, Skill.dwis20, Skill.lightning4)),
    new Array("40043", "Almighty Stymphalian Bird", "This bird is most beloved of the war god's minions, its steel body rivaling metals from the forges of the heavens.", 
              Event.none, Border.almighty, 5, Place.coliseum, 10, "40013", Shape.bird, Attribute.mecha,
              930, 910, 1037, 1600, 1127, 912,
              new Array(Skill.def20, Skill.ddef20, Skill.physical3, Skill.agi20, Skill.physical4),
              new Array(Skill.ddef20, Skill.agi20, Skill.physical4),
              new Array(Skill.ddef20, Skill.agi20, Skill.physical4)),
    new Array("40044", "Mighty Stymphalian Bird", "Servant to the god of war, each feather upon this metal bird's body bears an edge as sharp and deadly as its talons.", 
              Event.none, Border.mighty, 5, Place.coliseum, 10, "40013", Shape.bird, Attribute.mecha,
              930, 910, 1037, 1300, 1127, 912,
              new Array(Skill.def20, Skill.ddef20, Skill.physical3, Skill.agi20, Skill.physical4),
              new Array(Skill.ddef20, Skill.agi20, Skill.physical4),
              new Array(Skill.ddef20, Skill.agi20, Skill.physical4)),
    new Array("40063", "Almighty Vampire Matron", "This supreme matron of the undead has lived millennia, growing in strength with each bloodbound minion spawned by her red kiss.", 
              Event.none, Border.almighty, 5, Place.coliseum, 11, "40005", Shape.humanoid, Attribute.death,
              1350, 1007, 980, 960, 1008, 1002,
              new Array(Skill.life, Skill.darkness3, Skill.mana, Skill.revival, Skill.darkness4),
              new Array(Skill.darkness3, Skill.revival, Skill.darkness4),
              new Array(Skill.darkness3, Skill.revival, Skill.darkness4)),
    new Array("40064", "Mighty Vampire Matron", "This powers of this dark mother have grown over the centuries as she creates new children damned to feast on the blood of the living.", 
              Event.none, Border.mighty, 5, Place.coliseum, 11, "40005", Shape.humanoid, Attribute.death,
              1200, 1007, 980, 960, 1008, 1002,
              new Array(Skill.life, Skill.darkness3, Skill.mana, Skill.revival, Skill.darkness4),
              new Array(Skill.darkness3, Skill.revival, Skill.darkness4),
              new Array(Skill.darkness3, Skill.revival, Skill.darkness4)),
	new Array("40067", "Almighty Pumpkin Chunkin' Titan", "The wrath of this raging deity of old is nigh unstoppable when woken by the dark call of All Hallows' Eve.", 
              Event.none, Border.almighty, 5, Place.coliseum, 12, "40003", Shape.giant, Attribute.earth,
              1500, 1025, 1070, 1060, 910, 910,
              new Array(Skill.physical3, Skill.earth3, Skill.atk20, Skill.def20, Skill.physical4),
              new Array(Skill.atk20, Skill.def20, Skill.physical4),
              new Array(Skill.atk20, Skill.def20, Skill.physical4)),
    new Array("40068", "Mighty Pumpkin Chunkin' Titan", "Damned to rise every Halloween, this wicked god huris snarling pumpkins lit from within by fell flame.", 
              Event.none, Border.mighty, 5, Place.coliseum, 12, "40003", Shape.giant, Attribute.earth,
              1230, 1025, 1070, 1060, 910, 910,
              new Array(Skill.physical3, Skill.earth3, Skill.atk20, Skill.def20, Skill.physical4),
              new Array(Skill.atk20, Skill.def20, Skill.physical4),
              new Array(Skill.atk20, Skill.def20, Skill.physical4)),
    new Array("40072", "Almighty Banshee Witch", "The dread and fright of those haunted on Halloween drive this witch to ever greater power and purpose.", 
              Event.none, Border.almighty, 5, Place.coliseum, 13, null, Shape.humanoid, Attribute.death,
              1117, 930, 966, 1001, 1005, 1200,
              new Array(Skill.darkness3, Skill.ddef20, Skill.life, Skill.revival, Skill.darkness4),
              new Array(Skill.ddef20, Skill.revival, Skill.darkness4),
              new Array(Skill.ddef20, Skill.revival, Skill.darkness4)),
    new Array("40073", "Mighty Banshee Witch", "Damned to rise every Halloween, this wicked god hurls snarling pumpkins lit from within by fell flame.", 
              Event.none, Border.mighty, 5, Place.coliseum, 13, null, Shape.humanoid, Attribute.death,
              1047, 930, 996, 1001, 1005, 1099,
              new Array(Skill.darkness3, Skill.ddef20, Skill.life, Skill.revival, Skill.darkness4),
              new Array(Skill.ddef20, Skill.revival, Skill.darkness4),
              new Array(Skill.ddef20, Skill.revival, Skill.darkness4)),
	new Array("40026", "Almighty Frankenstein", "This being has attained great new strengths, having won its humanity in a bitter battle with its creator", 
              Event.none, Border.almighty, 5, Place.coliseum, 14, "40020", Shape.giant, Attribute.death,
              1200, 980, 1200, 1100, 955, 970,
              new Array(Skill.physical2, Skill.atk20, Skill.lightning3, Skill.physical3, Skill.physical4),
              new Array(Skill.atk20, Skill.physical3, Skill.physical4),
              new Array(Skill.atk20, Skill.physical3, Skill.physical4)),
    new Array("40027", "Mighty Frankenstein", "Driven to despair by his hideous appearance, this man-made monster vows vengeance upon his creator.", 
              Event.none, Border.mighty, 5, Place.coliseum, 14, "40020", Shape.giant, Attribute.death,
              1160, 911, 1160, 1100, 955, 970,
              new Array(Skill.physical2, Skill.atk20, Skill.lightning3, Skill.physical3, Skill.physical4),
              new Array(Skill.atk20, Skill.physical3, Skill.physical4),
              new Array(Skill.atk20, Skill.physical3, Skill.physical4)),
	new Array("40041", "Archfiend Azi Dahaka", "This creation of a sinister power bears three heads which visit pain, agony, and death upon all they see.", 
              Event.none, Border.almighty, 5, Place.coliseum, 15, "40014", Shape.wolf, Attribute.poison,
              10, 1030, 1600, 913, 1250, 1600,
              new Array(Skill.poison2, Skill.poison3, Skill.dagi20, Skill.dwis20, Skill.poison4),
              new Array(Skill.dagi20, Skill.dwis20, Skill.poison4),
              new Array(Skill.dagi20, Skill.dwis20, Skill.poison4)),
    new Array("40042", "Highfiend Azi Dahaka", "The evil god who made this dragon imbued the blood coursing through it with the power to end all life.", 
              Event.none, Border.mighty, 5, Place.coliseum, 15, "40014", Shape.wolf, Attribute.poison,
              10, 1030, 1200, 913, 1150, 1200,
              new Array(Skill.poison2, Skill.poison3, Skill.dagi20, Skill.dwis20, Skill.poison4),
              new Array(Skill.dagi20, Skill.dwis20, Skill.poison4),
              new Array(Skill.dagi20, Skill.dwis20, Skill.poison4)),
    new Array("40035", "Almighty Gargantua", "Ancient and now fully sentient, this instrument of war has a will to power so potent that the strength at its command is limitless.", 
              Event.none, Border.almighty, 5, Place.coliseum, 17, "40015", Shape.orbs, Attribute.mecha,
              1210, 914, 1200, 1020, 915, 940,
              new Array(Skill.atk10, Skill.physical3, Skill.slash3, Skill.atk20, Skill.physical4),
              new Array(Skill.atk10, Skill.atk20, Skill.physical4),
              new Array(Skill.atk10, Skill.atk20, Skill.physical4)),
    new Array("40036", "Mighty Gargantua", "The kernel of self has taken root in this massive war machine, and it now summons greater strength simply by thought alone.", 
              Event.none, Border.mighty, 5, Place.coliseum, 17, "40015", Shape.orbs, Attribute.mecha,
              1210, 914, 1200, 1020, 915, 940,
              new Array(Skill.atk10, Skill.physical2, Skill.physical3, Skill.slash3, Skill.physical4),
              new Array(Skill.atk10, Skill.slash3, Skill.physical4),
              new Array(Skill.atk10, Skill.slash3, Skill.physical4)),
	new Array("40045", "Almighty Apsara", "These ancient water spirits have existed since creation, and possess beauty and elegance enough to sedu...", 
              Event.none, Border.almighty, 5, Place.coliseum, 18, "40012", Shape.humanoid, Attribute.water,
              1560, 1170, 912, 910, 1062, 1130,
              new Array(Skill.water1, Skill.water2, Skill.agi20, Skill.dwis20, Skill.water4),
              new Array(Skill.agi20, Skill.dwis20, Skill.water4),
              new Array(Skill.agi20, Skill.dwis20, Skill.water4)),
    new Array("40046", "Mighty Apsara", "The most exalted of these spirits of water cloud soar the firmament, guiding the souls of fallen heroes to...", 
              Event.none, Border.mighty, 5, Place.coliseum, 18, "40012", Shape.humanoid, Attribute.water,
              1160, 1170, 912, 910, 1062, 1130,
              new Array(Skill.water1, Skill.water2, Skill.agi20, Skill.dwis20, Skill.water4),
              new Array(Skill.agi20, Skill.dwis20, Skill.water4),
              new Array(Skill.agi20, Skill.dwis20, Skill.water4)),
    new Array("40106", "Almighty Yuletide Lich", "This powerful lich knows who has been naughty and who has been nice, and on Christmas Eve the chimney of no home can deny her.", 
              Event.none, Border.almighty, 5, Place.coliseum, 19, null, Shape.humanoid, Attribute.death,
              1200, 1040, 959, 1001, 1120, 1200,
              new Array(Skill.life, Skill.dwis20, Skill.darkness4, Skill.light4, Skill.revival),
              new Array(Skill.dwis20, Skill.darkness4, Skill.revival),
              new Array(Skill.dwis20, Skill.darkness4, Skill.revival)),
    new Array("40107", "Mighty Yuletide Lich", "Returning from beyond the grave on the Eve of Yule, this jovial undead brings gifts and smiles to all with her midwinter magic.", 
              Event.none, Border.mighty, 5, Place.coliseum, 19, null, Shape.humanoid, Attribute.death,
              1075, 1040, 959, 1001, 1040, 1120,
              new Array(Skill.life, Skill.dwis20, Skill.darkness4, Skill.light4, Skill.revival),
              new Array(Skill.dwis20, Skill.darkness4, Skill.revival),
              new Array(Skill.dwis20, Skill.darkness4, Skill.revival)),
	new Array("40109", "Almighty Jolly Old Azi Dahaka", "This fiendish dragon turned good now toils to spread holiday cheer, using its magic to bring gifts and smiles to all.", 
              Event.none, Border.almighty, 5, Place.coliseum, 20, null, Shape.wolf, Attribute.poison,
              358, 280, 1520, 913, 1400, 1800,
              new Array(Skill.wis10, Skill.dwis20, Skill.light2, Skill.light3, Skill.ls),
              new Array(Skill.wis10, Skill.light2, Skill.ls),
              new Array(Skill.wis10, Skill.light2, Skill.ls)),
    new Array("40110", "Mighty Jolly Old Azi Dahaka", "Cleansed of evil by the holiday spirit, this dragon now appears in all its horror to punish the past year's naughty.", 
              Event.none, Border.mighty, 5, Place.coliseum, 20, null, Shape.wolf, Attribute.poison,
              358, 280, 1300, 913, 1320, 1500,
              new Array(Skill.wis10, Skill.dwis20, Skill.light2, Skill.light3, Skill.ls),
              new Array(Skill.wis10, Skill.light2, Skill.ls),
              new Array(Skill.wis10, Skill.light2, Skill.ls)),
	new Array("40112", "Almighty Christmas Banshee", "On the night before Christmas, the tears of this lamenting spirit take on the brilliance of stars and fill the firmament.", 
              Event.none, Border.almighty, 5, Place.coliseum, 21, null, Shape.humanoid, Attribute.death,
              1520, 1100, 930, 1001, 1120, 1220,
              new Array(Skill.death2, Skill.agi20, Skill.wis20, Skill.death3, Skill.death4),
              new Array(Skill.agi20, Skill.wis20, Skill.death4),
              new Array(Skill.agi20, Skill.wis20, Skill.death4)),
	new Array("40113", "Mighty Christmas Banshee", "The keening of this spirit on the eve of Yule becomes a hymn of benediction that echoes throughout the heavens.", 
              Event.none, Border.mighty, 5, Place.coliseum, 21, null, Shape.humanoid, Attribute.death,
              1220, 1100, 930, 1001, 1080, 1220,
              new Array(Skill.death2, Skill.agi20, Skill.wis20, Skill.death3, Skill.death4),
              new Array(Skill.agi20, Skill.wis20, Skill.death4),
              new Array(Skill.agi20, Skill.wis20, Skill.death4)),
    new Array("40075", "Maniacal Juggernaut", "This ancient battle tank is cursed by an unrelenting madness sated only by destruction and the blood of enemies.", 
              Event.none, Border.almighty, 5, Place.coliseum, 22, "40006", Shape.wolf, Attribute.mecha,
              666, 1720, 2300, 666, 666, 666,
              new Array(Skill.sd, Skill.physical2, Skill.slash2, Skill.physical3, Skill.qs),
              new Array(Skill.sd, Skill.physical3, Skill.qs),
              new Array(Skill.sd, Skill.physical3, Skill.qs)),
    new Array("40076", "Frenzied Juggernaut", "Forgers of ages past imbued this machine with a rage so potent that even its dying act is to obliterate all around it.", 
              Event.none, Border.mighty, 5, Place.coliseum, 22, "40006", Shape.wolf, Attribute.mecha,
              666, 1520, 2040, 666, 666, 666,
              new Array(Skill.sd, Skill.physical2, Skill.slash2, Skill.physical3, Skill.qs),
              new Array(Skill.sd, Skill.physical3, Skill.qs),
              new Array(Skill.sd, Skill.physical3, Skill.qs)),
    new Array("40488", "Almighty Horsemaiden Sleipnir", "This loyal attendant to the god of war is fated to face the wolf who eats the sun in the battle to come at the world's end.", 
              Event.none, Border.almighty, 5, Place.coliseum, 23, null, Shape.wolf, Attribute.earth,
              1160, 1100, 1100, 920, 1360, 1250,
              new Array(Skill.slash3, Skill.earth3, Skill.dwis20, Skill.qs, Skill.earth4),
              new Array(Skill.dwis20, Skill.qs, Skill.earth4),
              new Array(Skill.dwis20, Skill.qs, Skill.earth4)),
    new Array("40489", "Mighty Horsemaiden Sleipnir", "With a swiftness and stamina beyond that of any god or man, this warrioress is able to run for nine days without rest.", 
              Event.none, Border.mighty, 5, Place.coliseum, 23, null, Shape.wolf, Attribute.earth,
              1080, 1060, 1040, 920, 1280, 1120,
              new Array(Skill.slash3, Skill.earth3, Skill.dwis20, Skill.qs, Skill.earth4),
              new Array(Skill.dwis20, Skill.qs, Skill.earth4),
              new Array(Skill.dwis20, Skill.qs, Skill.earth4)),
	new Array("40060", "Almighty Raijin", "Unrivaled among the gods of thunder and lightning, this deity is able to fell any foe before him with blindingly fast bolts of levin.",
			  Event.none, Border.almighty, 5, Place.coliseum, 24, "40023", Shape.orbs, Attribute.lightning,
			  1165, 1029, 1176, 1071, 1400, 1150,
              new Array(Skill.physical2, Skill.physical3, Skill.lightning2, Skill.lightning3, Skill.lightning4),
              new Array(Skill.physical3, Skill.lightning3, Skill.lightning4),
              new Array(Skill.physical3, Skill.lightning3, Skill.lightning4)),
	new Array("40061", "Mighty Raijin", "Few are able to withstand the fury of this lightning god, who throws bolts down upon his enemies with untold power and speed.",
			  Event.none, Border.mighty, 5, Place.coliseum, 24, "40023", Shape.orbs, Attribute.lightning,
			  1110, 980, 1120, 1020, 1320, 1100,
              new Array(Skill.physical2, Skill.physical3, Skill.lightning2, Skill.lightning3, Skill.lightning4),
              new Array(Skill.physical3, Skill.lightning3, Skill.lightning4),
              new Array(Skill.physical3, Skill.lightning3, Skill.lightning4)),
	new Array("40065", "Almighty Fujin", "The winds obey this master over all others, growing to raging billows that carry his foes to blustery deaths.",
			  Event.none, Border.almighty, 5, Place.coliseum, 25, "40024", Shape.orbs, Attribute.wind,
			  1010, 1020, 1030, 1030, 1260, 1260,
              new Array(Skill.wind2, Skill.dwis20, Skill.wind3, Skill.agi20, Skill.wind4),
              new Array(Skill.dwis20, Skill.agi20, Skill.wind4),
              new Array(Skill.dwis20, Skill.agi20, Skill.wind4)),
	new Array("40066", "Mighty Fujin", "Wheresoever this fierce god goes, stormy gales follow, leaving in his path a wake of windswept death and ruin.",
			  Event.none, Border.mighty, 5, Place.coliseum, 25, "40024", Shape.orbs, Attribute.wind,
			  1010, 1020, 1030, 1030, 1133, 1133,
              new Array(Skill.wind2, Skill.dwis20, Skill.wind3, Skill.agi20, Skill.wind4),
              new Array(Skill.dwis20, Skill.agi20, Skill.wind4),
              new Array(Skill.dwis20, Skill.agi20, Skill.wind4)),
	new Array("40079", "Almighty Shiva", "This goddess rules a domain of deathly cold where all is frozen, and can turn whole armies to ice with but a breath.",
			  Event.none, Border.almighty, 5, Place.coliseum, 26, "40021", Shape.humanoid, Attribute.water,
			  1200, 1183, 1005, 1205, 1150, 1300,
              new Array(Skill.wis20, Skill.atk20, Skill.water3, Skill.water4, Skill.earth4),
              new Array(Skill.wis20, Skill.water4, Skill.earth4),
              new Array(Skill.wis20, Skill.water4, Skill.earth4)),
	new Array("40080", "Mighty Shiva", "All who have opposed this empress of ice now adorn her kingdom as frozen statues, a testament to her wintry wrath.",
			  Event.none, Border.mighty, 5, Place.coliseum, 26, "40021", Shape.humanoid, Attribute.water,
			  1012, 1183, 1002, 1028, 1050, 1200,
              new Array(Skill.wis20, Skill.atk20, Skill.water3, Skill.water4, Skill.earth4),
              new Array(Skill.wis20, Skill.water4, Skill.earth4),
              new Array(Skill.wis20, Skill.water4, Skill.earth4)),
	new Array("40082", "Almighty Chariot", "These beasts, rider, and carriage of steel charge with the force of a raging storm which no foe can weather.",
			  Event.none, Border.almighty, 5, Place.coliseum, 27, "40048", Shape.wolf, Attribute.mecha,
			  1240, 935, 1200, 1038, 1280, 950,
              new Array(Skill.qs, Skill.agi20, Skill.atk20, Skill.physical3, Skill.physical4),
              new Array(Skill.qs, Skill.atk20, Skill.physical4),
              new Array(Skill.qs, Skill.atk20, Skill.physical4)),
	new Array("40083", "Mighty Chariot", "Never at rest since the ancient age of its creation, this war machine leaves naught but death and ruin in its wake.",
			  Event.none, Border.mighty, 5, Place.coliseum, 27, "40048", Shape.wolf, Attribute.mecha,
			  1160, 935, 1160, 1038, 1200, 950,
              new Array(Skill.qs, Skill.agi20, Skill.atk20, Skill.physical3, Skill.physical4),
              new Array(Skill.qs, Skill.atk20, Skill.physical4),
              new Array(Skill.qs, Skill.atk20, Skill.physical4)),
	new Array("40070", "Almighty Lord of the Inferno", "",
			  Event.none, Border.almighty, 5, Place.coliseum, 28, "40013", Shape.giant, Attribute.fire,
			  1320, 1005, 1069, 1414, 957, 1200,
              new Array(Skill.fire3, Skill.def10, Skill.wis20, Skill.def20, Skill.fire4),
              new Array(Skill.wis20, Skill.def20, Skill.fire4),
              new Array(Skill.wis20, Skill.def20, Skill.fire4)),
	new Array("40071", "Mighty Lord of the Inferno", "",
			  Event.none, Border.mighty, 5, Place.coliseum, 28, "40013", Shape.giant, Attribute.fire,
			  1240, 1005, 1069, 1350, 957, 1150,
              new Array(Skill.fire3, Skill.def10, Skill.wis20, Skill.def20, Skill.fire4),
              new Array(Skill.wis20, Skill.def20, Skill.fire4),
              new Array(Skill.wis20, Skill.def20, Skill.fire4)),
	new Array("40150", "Almighty Valentine Specter", "Objects of this sweet maiden spirit's affections come to know the full beauty and terror of which love is capable.",
			  Event.none, Border.almighty, 5, Place.coliseum, 29, "40021", Shape.orbs, Attribute.death,
			  1360, 2680, 990, 990, 1280, 1184,
              new Array(Skill.sd, Skill.dagi20, Skill.dwis20, Skill.death4, Skill.wis20),
              new Array(Skill.sd, Skill.death4, Skill.wis20),
              new Array(Skill.sd, Skill.death4, Skill.wis20)),
	new Array("40151", "Mighty Valentine Specter", "Awkward and clumsy, this endearing departed's love often brings disaster, but she has only the purest intentions.",
			  Event.none, Border.mighty, 5, Place.coliseum, 29, "40021", Shape.orbs, Attribute.death,
			  1160, 2000, 990, 990, 1130, 1084,
              new Array(Skill.sd, Skill.dagi20, Skill.dwis20, Skill.death4, Skill.wis20),
              new Array(Skill.sd, Skill.death4, Skill.wis20),
              new Array(Skill.sd, Skill.death4, Skill.wis20)),
	new Array("40087", "Almighty Behemoth", "The very height of godly creation, this beast is nature's fury itself, and harbors a rage as great and terrible as its girth.",
			  Event.none, Border.almighty, 5, Place.coliseum, 30, "40056", Shape.beast, Attribute.earth,
			  1260, 940, 1320, 1720, 890, 1100,
              new Array(Skill.ls, Skill.earth2, Skill.def20, Skill.physical3, Skill.physical4),
              new Array(Skill.ls, Skill.def20, Skill.physical4),
              new Array(Skill.ls, Skill.def20, Skill.physical4)),
	new Array("40088", "Mighty Behemoth", "Though this immense beast is gentle by nature, neither the hand of man nor god can stay its wrath once woken.",
			  Event.none, Border.mighty, 5, Place.coliseum, 30, "40056", Shape.beast, Attribute.earth,
			  1149, 940, 1163, 1720, 890, 1100,
              new Array(Skill.ls, Skill.earth2, Skill.def20, Skill.physical3, Skill.physical4),
              new Array(Skill.ls, Skill.def20, Skill.physical4),
              new Array(Skill.ls, Skill.def20, Skill.physical4)),
	new Array("40095", "Almighty Dominion", "The symbol of her god's majesty and empowered to carry out his will, this divine being keeps the worldly order.",
			  Event.none, Border.almighty, 5, Place.coliseum, 31, "40009", Shape.humanoid, Attribute.light,
			  1200, 1080, 920, 1068, 1440, 1240,
              new Array(Skill.light3, Skill.majorheal, Skill.wis20, Skill.def20, Skill.light4),
              new Array(Skill.wis20, Skill.def20, Skill.light4),
              new Array(Skill.wis20, Skill.def20, Skill.light4)),
	new Array("40096", "Mighty Dominion", "Chosen to hear the final charge of her god at the end of days, this angel shall lead the descent of heaven's legions.",
			  Event.none, Border.mighty, 5, Place.coliseum, 31, "40009", Shape.humanoid, Attribute.light,
			  1100, 1020, 920, 1068, 1350, 1200,
              new Array(Skill.light3, Skill.majorheal, Skill.wis20, Skill.def20, Skill.light4),
              new Array(Skill.wis20, Skill.def20, Skill.light4),
              new Array(Skill.wis20, Skill.def20, Skill.light4)),
	new Array("40098", "Almighty Nuada", "This beloved godking is fated to battle the deadliest of the dark dragons, and will not rest or falter until victory is his.",
			  Event.none, Border.almighty, 5, Place.coliseum, 32, "40053", Shape.humanoid, Attribute.mecha,
			  1320, 977, 1280, 1103, 1003, 975,
              new Array(Skill.ls, Skill.atk20, Skill.physical3, Skill.slash3, Skill.physical4),
              new Array(Skill.ls, Skill.atk20, Skill.physical4),
              new Array(Skill.ls, Skill.atk20, Skill.physical4)),
   	 new Array("40099", "Mighty Nuada", "His arm remade with silver, this divine ruler swears to deliver his people from the fiendish tyrant who usurped him.",
			  Event.none, Border.mighty, 5, Place.coliseum, 32, "40053", Shape.humanoid, Attribute.mecha,
			  1200, 977, 1220, 1103, 1003, 975,
              new Array(Skill.ls, Skill.atk20, Skill.physical3, Skill.slash3, Skill.physical4),
              new Array(Skill.ls, Skill.atk20, Skill.physical4),
              new Array(Skill.ls, Skill.atk20, Skill.physical4)),
	new Array("40132", "Almighty Serenade Banshee", "So long as the gods grant her voice, this spirit of sad beauty shall sing in sorrow at the passing of saintly souls.",
			  Event.none, Border.almighty, 5, Place.coliseum, 33, "40054", Shape.female, Attribute.death,
			  1200, 1151, 959, 1001, 1080, 1220,
              new Array(Skill.death2, Skill.wis20, Skill.death3, Skill.death4, Skill.revival),
              new Array(Skill.wis20, Skill.death4, Skill.revival),
              new Array(Skill.wis20, Skill.death4, Skill.revival)),
	new Array("40133", "Mighty Serenade Banshee", "With her weeping wails, this kind spirit keeps at bay any evils seeking to claim good souls on their ascent to heaven.",
			  Event.none, Border.mighty, 5, Place.coliseum, 33, "40054", Shape.female, Attribute.death,
			  991, 1040, 959, 1001, 1039, 1220,
              new Array(Skill.death2, Skill.wis20, Skill.death3, Skill.death4, Skill.revival),
              new Array(Skill.wis20, Skill.death4, Skill.revival),
              new Array(Skill.wis20, Skill.death4, Skill.revival)),
	new Array("40125", "Almighty Agni", "This supreme being controls the existential force in all things, drawing upon it to ward evil and bring peace.",
			  Event.none, Border.almighty, 5, Place.coliseum, 34, null, Shape.humanoid, Attribute.fire,
			  1560, 1168, 1011, 995, 1024, 1240,
              new Array(Skill.fire4, Skill.earth4, Skill.water4, Skill.wind4, Skill.defwis10),
              new Array(Skill.fire4, Skill.wind4, Skill.defwis10),
              new Array(Skill.fire4, Skill.wind4, Skill.defwis10)),
	new Array("40126", "Mighty Agni", "With his undying flames, this red god purifies the world by burning away all evils and impurities lest they fester.",
			  Event.none, Border.mighty, 5, Place.coliseum, 34, null, Shape.humanoid, Attribute.fire,
			  1220, 1168, 1011, 977, 1024, 1160,
              new Array(Skill.fire4, Skill.earth4, Skill.water4, Skill.wind4, Skill.defwis10),
              new Array(Skill.fire4, Skill.wind4, Skill.defwis10),
              new Array(Skill.fire4, Skill.wind4, Skill.defwis10)),
	new Array("40121", "Almighty Bahamut", "As the true king of dark dragonkind, this god is an eternal fount of darkness threatening to envelop all life.",
			  Event.none, Border.almighty, 5, Place.coliseum, 35, null, Shape.bird, Attribute.darkness,
			  1480, 1084, 1190, 1026, 1120, 1110,
              new Array(Skill.atk20, Skill.fire3, Skill.physical4, Skill.wis20, Skill.darkness4),
              new Array(Skill.atk20, Skill.physical4, Skill.wis20),
              new Array(Skill.atk20, Skill.physical4, Skill.wis20)),
	new Array("40122", "Mighty Bahamut", "This draconic deity has existed since before time began, drawing its vast powers forth from primordial darkness.",
			  Event.none, Border.mighty, 5, Place.coliseum, 35, null, Shape.bird, Attribute.darkness,
			  1250, 1063, 1168, 1007, 1056, 1082,
              new Array(Skill.atk20, Skill.fire3, Skill.physical4, Skill.wis20, Skill.darkness4),
              new Array(Skill.atk20, Skill.physical4, Skill.wis20),
              new Array(Skill.atk20, Skill.physical4, Skill.wis20)),
	new Array("40129", "Archfiend Mictlantecuhtli", "Death and night fall under the dominion of this decayed king, whose wrath and guile see all his foes to a dark demise.",
			  Event.none, Border.almighty, 5, Place.coliseum, 36, null, Shape.orbs, Attribute.death,
			  10, 2443, 910, 1059, 1441, 1200,
              new Array(Skill.sd, Skill.wis20, Skill.poison3, Skill.poison4, Skill.wis25),
              new Array(Skill.sd, Skill.poison4, Skill.wis25),
              new Array(Skill.sd, Skill.poison4, Skill.wis25)),
	new Array("40130", "Highfiend Mictlantecuhtli", "None fated to die can escape the hand of this king of bones, who sits atop his hellish throne at the world's bottom.",
			  Event.none, Border.mighty, 5, Place.coliseum, 36, null, Shape.orbs, Attribute.death,
			  10, 1983, 910, 1059, 1351, 1148,
              new Array(Skill.sd, Skill.wis10, Skill.poison3, Skill.poison4, Skill.wis20),
              new Array(Skill.sd, Skill.poison4, Skill.wis20),
              new Array(Skill.sd, Skill.poison4, Skill.wis20)),
	new Array("40157", "Almighty Fortuna", "The fortune and fall of mortal men are born from the caprice of this goddess, whose wings form the ring of fate itself.",
			  Event.trials, Border.almighty, 5, Place.trials, 0, null, Shape.humanoid, Attribute.mecha,
			  1560, 1080, 1033, 1040, 996, 1150,
              new Array(Skill.wis10, Skill.darkness4, Skill.wis20, Skill.light4, Skill.wis25),
              new Array(Skill.wis20, Skill.darkness4, Skill.wis25),
              new Array(Skill.wis20, Skill.darkness4, Skill.wis25))

));

Card.addLimitedTypes({
    "40037": new Array(Type.cool, Type.coolr), // Iron Maiden
    "40038": new Array(Type.cool, Type.coolr), // Requiem Banshee
	"45000": new Array(Type.cool, Type.coolr), // Deadman Titan
	"40085": new Array(Type.cool), // Hellfire Vimana
	"40157": new Array(Type.cool, Type.coolr), // Almighty Fortuna
	"40159": new Array(Type.cool, Type.coolr), // Artemis
	"40160": new Array(Type.cool, Type.coolr), // Idun
	
	//Block Ace/rebirth for borders
	"40015": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40059": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40016": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40062": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40028": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40029": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40039": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40040": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40033": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40034": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40031": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40032": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40377": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40378": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40383": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40384": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40374": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40375": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40386": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40387": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40057": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40058": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40139": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40140": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40043": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40044": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40063": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40064": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40067": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40068": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40072": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40073": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40026": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40027": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40041": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40042": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40035": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40036": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40045": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40046": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40106": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40107": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40109": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40110": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40112": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40113": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40075": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40076": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40488": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40489": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40060": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40061": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40065": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40066": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40079": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40080": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40070": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40071": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40150": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40087": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40088": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40095": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40096": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40098": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40099": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),	
	"40132": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40125": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40126": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40121": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40122": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40129": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"40130": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr) //END bordered block	
});

Card.addNotes({
	"40147" : "Skills and stats not confirmed.",
	"40146" : "Skills and stats not confirmed.",
	"40144" : "Skills and stats not confirmed.",
	"40143" : "Skills and stats not confirmed.",
	"40126" : "Skills and stats not confirmed.",
	"40135" : "Skills and stats not confirmed.",
	"40136" : "Skills and stats not confirmed.",
	"40138" : "Skills and stats not confirmed.",
	"40132" : "Skills not confirmed.",
	"40133" : "Skills and stats not confirmed.",
	"40157": "card ID and skills not confirmed.",
	"40336": "RB skill not confirmed.",
    "40036": "Order of skills not confirmed.",
	"44004": "Card ID not confirmed.",
	"44005": "Card ID not confirmed.",
	"44006": "Card ID not confirmed.",
	"40488": "Shadow not confirmed.",
	"40489": "Skills and shadow not confirmed.",

	"40444": "Flavor text needed",
	"40150": new Array(Type.cool, Type.chaotic, Type.sexy, Type.brave, Type.powerful, Type.fast, Type.intelligent, Type.coolr, Type.bold, Type.erotic, Type.stalwart, Type.berserk, Type.sonic, Type.wise, Type.chaoticr, Type.sexyr, Type.braver, Type.powerfulr, Type.fastr, Type.intelligentr),
	"44002": "Flavor text needed",
	"44003": "Flavor text needed",
	"40446": "Flavor text needed",
	"44001": "Flavor text needed",
	"40445": "Flavor text needed",
	"45000": "Actual card ID unknown.  This one is only temporary."
});

ExCard.addAll(new Array(
/*     new Array("45001", "Kaneki", "",
              Event.none, ExType.red, 5, Place.plains_night, 0, Shape.giant, Attribute.fire,
              new Array(ExSkill.fire10, ExSkill.fire12, ExSkill.fire15)),
    new Array("45002", "Belphegor", "",
              Event.none, ExType.red, 5, Place.plains_night, 0, Shape.humanoid, Attribute.poison,
              new Array(ExSkill.poison10, ExSkill.poison12, ExSkill.poison15)),
    new Array("45003", "Ishtar", "",
              Event.none, ExType.red, 5, Place.plains_night, 0, Shape.female, Attribute.wind,
              new Array(ExSkill.atk10, ExSkill.atk12, ExSkill.atk15)),
    new Array("45004", "Asmodeus", "",
              Event.none, ExType.blue, 5, Place.plains_night, 0, Shape.wolf, Attribute.darkness,
              new Array(ExSkill.pow_curse20, ExSkill.pow_curse35, ExSkill.pow_curse50)),
    new Array("45005", "Muse", "",
              Event.none, ExType.blue, 5, Place.plains_night, 0, Shape.bird, Attribute.light,
              new Array(ExSkill.suc_revival10, ExSkill.suc_revival12, ExSkill.suc_revival15)) */
));
